### ISSUE TITLE
[BUG]: TypeError: model.transformReadItem is not a function

### ISSUE THREAD

**Issue by AndrewCathcart** [sensedeep/dynamodb-onetable#158]
**Describe the bug**
parseResponse does not behave correctly when extending from Model like so; 

```typescript
import { Entity, Model } from 'dynamodb-onetable';
import { Models, OneTable } from './aws/dynamo';

export type DepartmentEntity = Entity<typeof Models.Department>;

class Department extends Model<DepartmentEntity> {
  constructor() {
    super(OneTable, 'Department');
  }
}

export const DepartmentService = new Department();
```

It does however still work when using Table.getModel<T>('EntityName'), like so;

```typescript
import { Entity, Model } from 'dynamodb-onetable';
import { Models, OneTable } from './aws/dynamo';

export type TeamEntity = Entity<typeof Models.Team>;

export const TeamService: Model<TeamEntity> = OneTable.getModel<TeamEntity>('Team');
```

I believe the issue stems from the following lines;

https://github.com/sensedeep/dynamodb-onetable/blob/e9b07a4c224020f2f918b965c35786104b16afbe/src/Model.js#L450-L457

I monkey patched with some console.log's;

```typescript
/*
    Parse the response into Javascript objects and transform for the high level API.
 */
parseResponse(op, expression, items) {
    let { params, properties } = expression;
    let { schema, table } = this;
    if (op == 'put') {
        //  Put requests do not return the item. So use the properties.
        items = [properties];
    }
    else {
        items = table.unmarshall(items);
    }
    for (let [index, item] of Object.entries(items)) {
        if (params.high && params.index == this.indexes.primary && item[this.typeField] != this.name) {
            //  High level API on the primary index and item for a different model
            continue;
        }
        let type = item[this.typeField] ? item[this.typeField] : this.name;
        console.log('type: ', type)
        console.log('this: ', this)
        console.log('schema.models[type]:', schema.models[type])
        let model = schema.models[type] ? schema.models[type] : this;
        if (model) {
            if (model == schema.uniqueModel) {
                //  Special "unique" model for unique fields. Don't return in result.
                continue;
            }
            items[index] = model.transformReadItem(op, item, properties, params);
        }
    }
    return items;
}
```

```
type: Department

this:  n {
  table: Table {
    context: {},
    log: Log { logger: [Function: defaultLogger] },
    client: DocumentClient {
      options: [Object],
      service: [Service],
      attrValue: 'S6'
    },
    V3: undefined,
    service: Service {
      config: [Config],
      isGlobalEndpoint: false,
      endpoint: [Endpoint],
      _events: [Object],
      MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
      CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
      _clientId: 1
    },
    createdField: 'created',
    delimiter: '#',
    hidden: true,
    isoDates: false,
    nulls: false,
    timestamps: false,
    typeField: '_type',
    updatedField: 'updated',
    name: 'dev-ino',
    intercept: undefined,
    transform: undefined,
    makeID: [Function: uuid],
    params: {
      name: 'dev-ino',
      client: [DocumentClient],
      schema: [Object],
      uuid: [Function: uuid],
      logger: true
    },
    schema: Schema {
      params: [Object],
      models: [Object],
      indexes: [Object],
      uniqueModel: [Model],
      genericModel: [Model],
      schemaFields: [Object],
      migrationFields: [Object],
      schema: [Object]
    }
  },
  name: 'Department',
  options: {},
  schema: {
    version: '0.0.1',
    models: { Department: [Object], Team: [Object], User: [Object] },
    indexes: { primary: [Object], gsi1: [Object], gsi2: [Object] }
  },
  hash: 'pk',
  sort: 'sk',
  createdField: 'created',
  delimiter: '#',
  generic: undefined,
  nested: false,
  nulls: false,
  tableName: 'dev-ino',
  typeField: '_type',
  timestamps: false,
  updatedField: 'updated',
  indexes: {
    primary: { hash: 'pk', sort: 'sk', description: 'Primary Index' },
    gsi1: {
      hash: 'gsi1pk',
      sort: 'gsi1sk',
      description: 'Secondary Index 1',
      project: 'all'
    },
    gsi2: {
      hash: 'gsi2pk',
      sort: 'gsi2sk',
      description: 'Secondary Index 2',
      project: 'all'
    }
  },
  indexProperties: {
    pk: 'primary',
    sk: 'primary',
    gsi1pk: 'gsi1',
    gsi1sk: 'gsi1',
    gsi2pk: 'gsi2',
    gsi2sk: 'gsi2'
  },
  block: {
    fields: {
      pk: [Object],
      sk: [Object],
      gsi1pk: [Object],
      gsi1sk: [Object],
      departmentName: [Object],
      departmentId: [Object],
      _type: [Object]
    },
    deps: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  mappings: {}
}

schema.models[type]: {
  pk: { type: [Function: String], value: 'dept#${departmentId}' },
  sk: { type: [Function: String], value: 'A' },
  gsi1pk: { type: [Function: String], value: '${_type}' },
  gsi1sk: { type: [Function: String], value: 'dept#${departmentId}' },
  departmentName: { type: [Function: String], required: true },
  departmentId: { type: [Function: String], uuid: true }
}

```

which then ultimately leads to;

```
TypeError: model.transformReadItem is not a function
    at n.parseResponse (/var/task/node_modules/dynamodb-onetable/dist/cjs/Model.js:451:38)
    at n.<anonymous> (/var/task/node_modules/dynamodb-onetable/dist/cjs/Model.js:351:30)
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/node_modules/dynamodb-onetable/dist/cjs/Model.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**
Hopefully I've provided enough info above. If you require more code just let me know.

**Expected behavior**
parseResponse actually parses the response from dynamo instead of resulting in a TypeError

**Environment (please complete the following information):**
 - OS - macOS Catalina v10.15.7
 - Node Version - 14.17.6
 - dynamodb-onetable v1.9.4

**Comment by mobsense** [comment]
Thanks for reporting and we're working on this one. Should have an update later today.

**Comment by mobsense** [comment]
The fix is a little diffuse. Basically we refactored the schema code into ./Schema.js in recent releases. In doing this, Model.js referred to this.schema. However in some cases, this.schema as referring to a Schema class instance and in other cases it was referring to the actual schema JSON definition.

When creating a stand-alone model, it was using the JSON reference rather than the class reference. So the transform* methods were not present.

The fix required all models always using this.schema to refer to a Schema class instance and saving the JSON definition as this.schema.definition.

**Comment by mobsense** [comment]
Published now.
