### ISSUE TITLE
Nested array object is returning an error

### ISSUE THREAD

**Issue by umairyounus** [sensedeep/dynamodb-onetable#215]
**Nested array object is returning an error**
I have an array property with a nested object, but when I try to do an insert it's returning an error.

**To Reproduce**

Steps to reproduce the behaviour:

Schema:
```javascript
export const schema = {
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
  },
  models: {

    Company: {
      pk: { type: String, value: 'company:${companyId}' },
      sk: { type: String, value: 'profile' },
      companyId: { type: String, uuid: 'ulid' },
      companyTitle: { type: String, required: true },
      createdAt: { type: Date, required: true },
      updatedAt: { type: Date, required: true },
    },
    CompanyEmployee: {
      pk: { type: String, value: 'company:${company.companyId}' },
      sk: { type: String, value: 'employee:${companyEmployeeId}' },
      companyEmployeeId: { type: String, uuid: 'ulid', required: true },
      company: {
        type: Object,
        schema: {
          companyId: { type: String, uuid: 'ulid' },
          companyTitle: { type: String },
        },
      },
      firstName: { type: String, required: true },
      lastName: { type: String, required: true },
      email: { type: String, required: true },
      selfAssessment: { type: Boolean, required: true },
      superiors: {
        type: Array,
        schema: {
          companyEmployeeId: { type: String, uuid: 'ulid', required: true },
          firstName: { type: String, required: true },
          lastName: { type: String, required: true },
        },
      },
      peers: {
        type: Array,
        schema: {
          companyEmployeeId: { type: String, uuid: 'ulid', required: true },
          firstName: { type: String, required: true },
          lastName: { type: String, required: true },
        },
      },
      subordinates: {
        type: Array,
        schema: {
          companyEmployeeId: { type: String, uuid: 'ulid', required: true },
          firstName: { type: String, required: true },
          lastName: { type: String, required: true },
        },
      },
      createdAt: { type: Date, required: true },
      updatedAt: { type: Date, required: true },
    },
  } as const,
};
```

When I create a new Employee:
```javascript
await companyEmployeeModel.create({
  company: {
     companyId: '015ENZS901RKQ8IEQ09SX1C4VS',
     companyTitle: 'U85 Tech Ltd'
   },
   firstName: 'Arron',
   lastName: 'Finch',
   email: 'aron@email.co.uk',
   selfAssessment: false,
   superiors: [
    {
       companyEmployeeId: '015EP0BDFFASXRGR7DJZCIDF7S',
       firstName: 'John',
      lastName: 'Doe'
     }
   ],
  createdAt: 2021-12-03T11:38:16.964Z,
  updatedAt: 2021-12-03T11:38:16.964Z
});
```

It's returning an error:
```
TypeError: Cannot read property 'fields' of undefined
at Model.collectProperties (node_modules/dynamodb-onetable/dist/cjs/Model.js:965:28)
at Model.collectProperties (node_modules/dynamodb-onetable/dist/cjs/Model.js:975:26)
at Model.prepareProperties (node_modules/dynamodb-onetable/dist/cjs/Model.js:904:2)
```

`field.block` doesn't exist for `superiors` (which is an array)

There must be something wrong with the schema definition for `superiors`

**Comment by mobsense** [comment]
The issue is you are using nested schemas on Array type items.  This is not yet supported.

For now, comment out the schema. You won't get TS types for them, but when we do support it, hopefully soon, you can uncomment.

**Comment by umairyounus** [comment]
ok, thanks.

**Comment by mobsense** [comment]
> oh, actually, i think it is working I take it back. The solution proposed here seems to work? ![image](https://user-images.githubusercontent.com/96137839/247331139-d025dc5e-a066-417f-bde5-2e51fcdebf27.png)

Can you post the link to that issue / discussion?
