### ISSUE TITLE
Issues with Paging find results

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#22]
result.start => `{"pk":{"S":"user#eWR6pYoybfADt4oBM"},"sk":{"S":"message#01F3F63MWN6H104E0698RN1XZ0"}}`

`start` param => `{"pk":{"S":"user#eWR6pYoybfADt4oBM"},"sk":{"S":"message#01F3F63MWN6H104E0698RN1XZ0"}}`

They are exactly the same, but adding the start param results in this error:

```
2021-04-18T04:32:49.623Z	9945dda7-db39-4e55-be9a-dc1119352034	ERROR	Invoke Error 	{"errorType":"ValidationException","errorMessage":"The provided key element does not match the schema","__type":"com.amazon.coral.validate#ValidationException","name":"ValidationException","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"JH9CAULMN2P18723AI80A7GF3RVV4KQNSO5AEMVJF66Q9ASUAAJG","attempts":1,"totalRetryDelay":0},"stack":["ValidationException: The provided key element does not match the schema","    at s9i (/var/node_modules/@aws-sdk/client-dynamodb/protocols/Aws_json1_0.ts:3704:39)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at /var/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18","    at /var/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22","    at ZHe.retry (/var/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)","    at /var/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20","    at GEe.send (/var/node_modules/dynamodb-onetable/dist/mjs/Dynamo.js:61:16)","    at GEe.find (/var/node_modules/dynamodb-onetable/dist/mjs/Dynamo.js:30:16)","    at V8.run (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:252:30)","    at V8.queryItems (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:528:16)"]}
```

**Comment by bytekast** [comment]
Workaround:
```
import { unmarshall } from '@aws-sdk/util-dynamodb'
```
I've had to `unmarshall` the start object before passing it in the params.

**Comment by mobsense** [comment]
Can you post the code segment to do that so I know exactly what is being unmarshalled?

**Comment by mobsense** [comment]
Would this patch address the issue:

```
diff --git a/src/Model.js b/src/Model.js
index 424dd4c..fc90fe6 100644
--- a/src/Model.js
+++ b/src/Model.js
@@ -334,7 +334,7 @@ export class Model {
         }
         if (op == 'find' || op == 'scan') {
             if (metrics) {
-                items.start = result.LastEvaluatedKey
+                items.start = this.table.unmarshall(result.LastEvaluatedKey)
             }
             if (result.LastEvaluatedKey) {
                 /*
```

**Comment by bytekast** [comment]
yep. I think this should work
