### ISSUE TITLE
Fields param is not working while fetching multipe entities

### ISSUE THREAD

**Issue by umairyounus** [sensedeep/dynamodb-onetable#230]
Fields filter does not work if you try to fetch multiple entities. 

**Schema:**

```javascript
export const schema = {
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
  },
  models: {
    Company: {
      pk: { type: String, value: 'company:${companyId}' },
      sk: { type: String, value: 'profile' },
      companyId: { type: String, uuid: 'ulid', required: true },
      companyTitle: { type: String, required: true },
    },
    CompanyEmployee: {
      pk: { type: String, value: 'company:${company.companyId}' },
      sk: { type: String, value: 'employee:${companyEmployeeId}' },
      companyEmployeeId: { type: String, uuid: 'ulid', required: true },
      company: {
        required: true,
        type: Object,
        schema: {
          companyId: { type: String, uuid: 'ulid', required: true },
        },
      },
      firstName: { type: String, required: true },
      lastName: { type: String, required: true },
      email: { type: String, required: true }
    },
  }
};
```

**Fetch Query:**

```javascript
await table.fetch(
  ['Company', 'CompanyEmployee'],
  {
    pk: `company:${companyId}`,
  },
  {
    fields: ['companyId', 'companyEmployeeId']
  },
)
```

The above fetch query returns this error:
```javascript
      {
        level: 'error',
        message: "Cannot read property 'attribute' of undefined",
        stack: "TypeError: Cannot read property 'attribute' of undefined\n" +
          '    at Expression.prepare (node_modules/dynamodb-onetable/dist/cjs/Expression.js:110:68)\n' +
          '    at new Expression (node_modules/dynamodb-onetable/dist/cjs/Expression.js:15:14)\n' +
          '    at Model.<anonymous> (node_modules/dynamodb-onetable/dist/cjs/Model.js:765:30)\n' +
          '    at Generator.next (<anonymous>)\n' +
          '    at node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at Object.<anonymous>.__awaiter (node_modules/dynamodb-onetable/dist/cjs/Model.js:4:12)\n' +
          '    at Model.queryItems (node_modules/dynamodb-onetable/dist/cjs/Model.js:762:16)\n' +
          '    at Model.<anonymous> (node_modules/dynamodb-onetable/dist/cjs/Model.js:815:36)\n' +
          '    at Generator.next (<anonymous>)\n' +
          '    at node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at Object.<anonymous>.__awaiter (node_modules/dynamodb-onetable/dist/cjs/Model.js:4:12)\n' +
          '    at Model.fetch (node_modules/dynamodb-onetable/dist/cjs/Model.js:798:16)\n' +
          '    at Table.<anonymous> (node_modules/dynamodb-onetable/dist/cjs/Table.js:660:51)\n' +
          '    at Generator.next (<anonymous>)'
      }
```

It seems like since both entities have different attributes and they are not present on all the collections, which results in undefined.

**Comment by mobsense** [comment]
I think the issue is companyEmployeeId is not a valid field for Company.

**Comment by umairyounus** [comment]
@mobsense that is correct, both entities fields are different. Is it still possible to specify the fields?

**Comment by mobsense** [comment]
Can you check with 2.2.1 which should not create an exception.
