### ISSUE TITLE
Reserved keywords (such as 'name', or 'other') used in keys not properly handled

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#242]
**Describe the bug**
Create a table with hash key ```name```. When an item is created, an error is encountered:
```
ValidationException: Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: name
```

**Cut/Paste**

test/debug.ts
```
import { inspect } from 'util';
import {AWS, Client, Match, Table, print, dump, delay} from './utils/init'

const Schema = {
  indexes: {
    primary: { hash: "name" },
  },
  models: {
    User: {
      name: {
        type: String,
      },
    }
  },
  version: "0.1.0",
  format: "onetable:1.0.0"
}

const name = 'Peter'

const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema: Schema,
    logger: (level, message, context) => {
        // if (level == 'trace' || level == 'data') return
        const contextMessage = context ? `Context: ${inspect(context, false, null)}` : ''
        console.log(`At: ${new Date().toISOString()}\nLevel: ${level}\nMessage: ${message}\n${contextMessage}`)
    }
})

test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Create item', async() => {
    const User = table.getModel('User')
    const user: any = await User.create({ name })
    expect(user).toBeDefined()
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```

STDOUT:
```
Using local Java to run dynamoDB
Spawn DynamoDB 5693
Waiting for 0.0.0.0:4567...
Connected!
DynamoDB is ready
  console.log
    At: 2022-01-06T05:39:58.032Z
    Level: trace
    Message: Loading OneTable

      at Log.logger (test/debug.ts:28:17)

  console.log
    At: 2022-01-06T05:39:58.467Z
    Level: trace
    Message: OneTable createTable for "DebugTable"
    Context: {
      def: {
        AttributeDefinitions: [ { AttributeName: 'name', AttributeType: 'S' } ],
        KeySchema: [ { AttributeName: 'name', KeyType: 'HASH' } ],
        TableName: 'DebugTable',
        BillingMode: 'PAY_PER_REQUEST'
      }
    }

      at Log.logger (test/debug.ts:28:17)

  console.log
    At: 2022-01-06T05:39:58.559Z
    Level: trace
    Message: OneTable "put" "User"
    Context: {
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: 'attribute_not_exists(name)',
          TableName: 'DebugTable',
          Item: { name: { S: 'Peter' }, _type: { S: 'User' } },
          ReturnValues: 'NONE'
        },
        op: 'put',
        properties: { name: 'Peter', _type: 'User' }
      }
    }

      at Log.logger (test/debug.ts:28:17)

  console.log
    At: 2022-01-06T05:39:58.734Z
    Level: error
    Message: OneTable exception in "put" on "User"
    Context: {
      err: ValidationException: Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: name
          at deserializeAws_json1_0PutItemCommandError (./node_modules/.pnpm/@aws-sdk+client-dynamodb@3.45.0/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2905:41)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at ./node_modules/.pnpm/@aws-sdk+middleware-serde@3.40.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
          at ./node_modules/.pnpm/@aws-sdk+middleware-signing@3.45.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
          at StandardRetryStrategy.retry (./node_modules/.pnpm/@aws-sdk+middleware-retry@3.40.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
          at ./node_modules/.pnpm/@aws-sdk+middleware-logger@3.40.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
          at Dynamo.send (./src/Dynamo.js:114:16)
          at Dynamo.put (./src/Dynamo.js:80:16)
          at Table.execute (./src/Table.js:513:26)
          at Model.run (./src/Model.js:328:22) {
        __type: 'com.amazon.coral.validate#ValidationException',
        '$fault': 'client',
        '$metadata': {
          httpStatusCode: 400,
          requestId: '7d8ef0ff-0e4f-4500-b505-ad5f8d0f3010',
          extendedRequestId: undefined,
          cfId: undefined,
          attempts: 1,
          totalRetryDelay: 0
        }
      },
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: 'attribute_not_exists(name)',
          TableName: 'DebugTable',
          Item: { name: { S: 'Peter' }, _type: { S: 'User' } },
          ReturnValues: 'NONE'
        },
        op: 'put',
        properties: { name: 'Peter', _type: 'User' },
        err: ValidationException: Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: name
            at deserializeAws_json1_0PutItemCommandError (./node_modules/.pnpm/@aws-sdk+client-dynamodb@3.45.0/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2905:41)
            at processTicksAndRejections (internal/process/task_queues.js:95:5)
            at ./node_modules/.pnpm/@aws-sdk+middleware-serde@3.40.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
            at ./node_modules/.pnpm/@aws-sdk+middleware-signing@3.45.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
            at StandardRetryStrategy.retry (./node_modules/.pnpm/@aws-sdk+middleware-retry@3.40.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
            at ./node_modules/.pnpm/@aws-sdk+middleware-logger@3.40.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
            at Dynamo.send (./src/Dynamo.js:114:16)
            at Dynamo.put (./src/Dynamo.js:80:16)
            at Table.execute (./src/Table.js:513:26)
            at Model.run (./src/Model.js:328:22) {
          __type: 'com.amazon.coral.validate#ValidationException',
          '$fault': 'client',
          '$metadata': {
            httpStatusCode: 400,
            requestId: '7d8ef0ff-0e4f-4500-b505-ad5f8d0f3010',
            extendedRequestId: undefined,
            cfId: undefined,
            attempts: 1,
            totalRetryDelay: 0
          }
        }
      }
    }

      at Log.logger (test/debug.ts:28:17)

  console.log
    At: 2022-01-06T05:39:58.737Z
    Level: trace
    Message: OneTable deleteTable for "DebugTable"

      at Log.logger (test/debug.ts:28:17)

```

STDERR:
```
FAIL test/debug.ts (9.187 s)
  ✓ Create Table (463 ms)
  ✕ Create item (180 ms)
  ✓ Destroy Table (18 ms)

  ● Create item

    OneError: OneTable execute failed "put" for "User. Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: name

      532 |                     this.log.error(`OneTable exception in "${op}" on "${model}"`, {err, trace})
      533 |                 }
    > 534 |                 throw new OneError(`OneTable execute failed "${op}" for "${model}. ${err.message}`, {err})
          |                       ^
      535 |             }
      536 |
      537 |         } finally {

      at Table.execute (src/Table.js:534:23)
      at Model.run (src/Model.js:328:22)
      at Model.putItem (src/Model.js:765:16)
      at Model.create (src/Model.js:488:22)
      at Object.<anonymous> (test/debug.ts:41:23)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        9.243 s, estimated 10 s
Ran all test suites matching /debug.ts/i.
```

**Expected behavior**
Expect creating an item to succeed.

**Environment (please complete the following information):**
 - OS ```Linux [...] 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
 - Node Version v14.18.2
 - OneTable Version "2.2.2"
 - TypeScript Version "^4.4.0"

**Additional context**
in
```
ConditionExpression: 'attribute_not_exists(name)',
```
the attribute name (_name_ in this example) needs to be escaped via indirection.

**Comment by mobsense** [comment]
A workaround for now is to use params of:

{ exists: null }

Of course, that has other side effects if the item already exists.

**Comment by mobsense** [comment]
Got a fix for this. Unfortunately, not just a few lines.

Will add to the next release due within a week, unless this causes real discomfort. Let me know.

**Comment by mobsense** [comment]
Fixed.

**Comment by adrian-grajdeanu** [comment]
Not a blocker for me now. Just found the issue when I was trying to construct a minimal code for a different matter. A fix can come in due course as far as i am concerned.

Jan 6, 2022 02:08:13 mobsense ***@***.***>:
