### ISSUE TITLE
Better validation needed for LSIs

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#243]
**Describe the bug**
From the documentation: 
"The schema.indexes property can contain one or more indexes and must contain the primary key. Additional indexes will be treated as Local Secondary Indexes (LSIs) if they only contain as sort key or if they set the hash key to the same value the primary index hash key. They will be treated as Global Secondary Indexes (GSIs) if they provide a unique hash key value."

The above rule is fine in many cases, but in general can be wrong. LSI are way more limited than GSI.
 * Must be created when the table is created; This means that a table cannot be updated to create a new index (that defaults to LSI according to the rule) in a subsequent deployment
 * Having LSI adds a 10GB limit to any single item collection
 * There can be up to five local secondary indexes per table; this is a hard limit; The limit for GSI is 20 and is soft.

**Cut/Paste**

test/debug.ts
```
import { inspect } from 'util';
import {AWS, Client, Match, Table, Entity, print, dump, delay} from './utils/init'

const Schema = {
  indexes: {
    primary: { hash: 'id', sort: 'nam0' },
    gsi1:    { hash: 'id', sort: 'nam1' },
    gsi2:    { hash: 'id', sort: 'nam2' },
    gsi3:    { hash: 'id', sort: 'nam3' },
    gsi4:    { hash: 'id', sort: 'nam4' },
    gsi5:    { hash: 'id', sort: 'nam5' },
    gsi6:    { hash: 'id', sort: 'nam6' },
  },
  models: {
    User: {
      id: { type: String, },
      nam0: { type: String, },
      nam1: { type: String, },
      nam2: { type: String, },
      nam3: { type: String, },
      nam4: { type: String, },
      nam5: { type: String, },
      nam6: { type: String, },
    },
  },
  version: "0.1.0",
  format: "onetable:1.0.0"
}

type UserType = Entity<typeof Schema.models.User>;

const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema: Schema,
    logger: (level, message, context) => {
        // if (level == 'trace' || level == 'data') return
        const contextMessage = context ? `Context: ${inspect(context, false, null)}` : ''
        console.log(`At: ${new Date().toISOString()}\nLevel: ${level}\nMessage: ${message}\n${contextMessage}`)
    }
})


test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```

Output of running test:
```
$ pnpx jest debug1.ts
Determining test suites to run...Using local Java to run dynamoDB
Spawn DynamoDB 28866
Waiting for 0.0.0.0:4567..
Connected!
DynamoDB is ready
  console.log
    At: 2022-01-11T00:28:36.831Z
    Level: trace
    Message: Loading OneTable

      at Log.logger (test/debug1.ts:39:17)

 FAIL  test/debug1.ts (6.461 s)
  ✕ Create Table (433 ms)
  ✕ Destroy Table (11 ms)

  ● Create Table

    ValidationException: Cannot have more than 5 local secondary indexes per table

      112 |
      113 |     async send(cmd) {
    > 114 |         return await this.client.send(cmd)
          |                ^
      115 |     }
      116 | }
      117 |

      at deserializeAws_json1_0CreateTableCommandError (node_modules/.pnpm/@aws-sdk+client-dynamodb@3.45.0/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:973:41)
      at node_modules/.pnpm/@aws-sdk+middleware-serde@3.40.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
      at node_modules/.pnpm/@aws-sdk+middleware-signing@3.45.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
      at StandardRetryStrategy.retry (node_modules/.pnpm/@aws-sdk+middleware-retry@3.40.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
      at node_modules/.pnpm/@aws-sdk+middleware-logger@3.40.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
      at Dynamo.send (src/Dynamo.js:114:16)
      at Dynamo.createTable (src/Dynamo.js:45:16)
      at Table.createTable (src/Table.js:263:20)
      at Object.<anonymous> (test/debug1.ts:46:9)

  ● Destroy Table

    ResourceNotFoundException: ResourceNotFoundException

      112 |
      113 |     async send(cmd) {
    > 114 |         return await this.client.send(cmd)
          |                ^
      115 |     }
      116 | }
      117 |

      at deserializeAws_json1_0DeleteTableCommandError (node_modules/.pnpm/@aws-sdk+client-dynamodb@3.45.0/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1234:41)
      at node_modules/.pnpm/@aws-sdk+middleware-serde@3.40.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
      at node_modules/.pnpm/@aws-sdk+middleware-signing@3.45.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
      at StandardRetryStrategy.retry (node_modules/.pnpm/@aws-sdk+middleware-retry@3.40.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
      at node_modules/.pnpm/@aws-sdk+middleware-logger@3.40.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
      at Dynamo.send (src/Dynamo.js:114:16)
      at Dynamo.deleteTable (src/Dynamo.js:50:16)
      at Table.deleteTable (src/Table.js:286:17)
      at Object.<anonymous> (test/debug1.ts:52:5)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        6.555 s, estimated 7 s
Ran all test suites matching /debug1.ts/i.
  console.log
    At: 2022-01-11T00:28:37.243Z
    Level: trace
    Message: OneTable createTable for "DebugTable"
    Context: {
      def: {
        AttributeDefinitions: [
          { AttributeName: 'id', AttributeType: 'S' },
          { AttributeName: 'nam0', AttributeType: 'S' },
          { AttributeName: 'nam1', AttributeType: 'S' },
          { AttributeName: 'nam2', AttributeType: 'S' },
          { AttributeName: 'nam3', AttributeType: 'S' },
          { AttributeName: 'nam4', AttributeType: 'S' },
          { AttributeName: 'nam5', AttributeType: 'S' },
          { AttributeName: 'nam6', AttributeType: 'S' }
        ],
        KeySchema: [
          { AttributeName: 'id', KeyType: 'HASH' },
          { AttributeName: 'nam0', KeyType: 'RANGE' }
        ],
        LocalSecondaryIndexes: [
          {
            IndexName: 'gsi1',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam1', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          },
          {
            IndexName: 'gsi2',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam2', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          },
          {
            IndexName: 'gsi3',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam3', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          },
          {
            IndexName: 'gsi4',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam4', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          },
          {
            IndexName: 'gsi5',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam5', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          },
          {
            IndexName: 'gsi6',
            KeySchema: [
              { AttributeName: 'id', KeyType: 'HASH' },
              { AttributeName: 'nam6', KeyType: 'RANGE' }
            ],
            Projection: { ProjectionType: 'ALL' }
          }
        ],
        TableName: 'DebugTable',
        BillingMode: 'PAY_PER_REQUEST'
      }
    }

      at Log.logger (test/debug1.ts:39:17)

  console.log
    At: 2022-01-11T00:28:37.301Z
    Level: trace
    Message: OneTable deleteTable for "DebugTable"

      at Log.logger (test/debug1.ts:39:17)
$
```

**Expected behavior**
I expect to have the ability to designate indexes as being global.

**Additional Information**
I propose adding a field to the index description that informs the library that an index should be created and treated as global. This is the easiest in terms of backwards compatibility. For instance:
```
const Schema = {
  indexes: {
    primary: { hash: 'id', sort: 'nam0' },
    gsi1: { hash: 'id', sort: 'nam1' , global: true },
    lsi1: { /*hash: 'id', */sort: 'nam2' }, // incidentally, here one should not be able to specify hash!
  }
  // ...
}
```
Alternatively the schema could allow describing indexes under gsi and lsi keys, which should be parallel to primary key. For instance:
```
const Schema = {
  indexes: {
    primary: { hash: 'id', sort: 'nam0' },
    gsi: { gsi1: { hash: 'id', sort: 'nam1' },/* other gsi*/},
    lsi: { lsi1: { /*hash: 'id', */sort: 'nam2' }, /*other lsi*/},  // incidentally, here one should not be able to specify hash!
  }
  // ...
}
```

**Comment by mobsense** [comment]
Yes, LSIs are very restrictive and inflexible. 

Thanks for the bug report. We should validate these inputs better.

**Comment by mobsense** [comment]
Currently we have implemented but not documented an index.type property that can be set to 'local' or 'global'.

For example:

```
const Schema = {
  indexes: {
    primary: { hash: 'id', sort: 'nam0' },
    gsi: { gsi1: { hash: 'id', sort: 'nam1' },
    lsi: { lsi1: {sort: 'nam1', type: local },
}
```

If type is unset, it is set to 'local' only if there is no hash defined or if the has is the same as the primary hash. i.e. Indexes will default to GSIs. 

I don't want to require a "type: global", because this is the default case for nearly all uses. LSIs are much more rarely used. However, we could tighten this up and insist that "type: local" is required for LSIs and that hash must not be set.

**Comment by adrian-grajdeanu** [comment]
So the undocumented field may provide a workaround.

The default behavior when hash is provided and is same with primary is problematic. But if the above field is documented it should work.

Jan 15, 2022 20:04:03 mobsense ***@***.***>:

**Comment by mobsense** [comment]
We've committed the proposed change and README with doc. If you provide a hash == primary.hash, we warn and set type == local. In the next release, we can make that a hard error.

**Comment by mobsense** [comment]
For all the issues submitted, I think we've committed fixes. This is in pre-release status. Please check it out and see if it addresses all issues. I'd like to fix any omissions before release.
