### ISSUE TITLE
Field not updated if part of index key

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#244]
**Describe the bug**
A request to update an item omits changes to a field if that field is part of index (gsi/lsi) hash/sort key.

**Cut/Paste**

test/debug.ts
```
import { inspect } from 'util';
import {AWS, Client, Match, Table, Entity, print, dump, delay} from './utils/init'

const Schema = {
  indexes: {
    //primary: { hash: 'id', sort: 'othr' },  // with this schema the test succeeds
    //primary: { hash: 'id', sort: 'othr', }, gsi: { hash: 'id', sort: 'nam' }, // with this schema the test fails
    primary: { hash: 'id', sort: 'othr' }, gsi: { hash: 'nam' }, // with this schema the test fails
  },
  models: {
    User: {
      id: { type: String, }, nam: { type: String, }, othr: { type: String, },
    },
  },
  version: "0.1.0",
  params: {
    timestamps: true,
    isoDates: true,
    typeField: 'type',
  },
  format: "onetable:1.0.0"
}

type UserType = Entity<typeof Schema.models.User>;

const id = 'aswpfhaeswr'
const nam = 'foo'
const nameOther = 'bar'
const othr = 'othr'

const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema: Schema,
    logger: (level, message, context) => {
        // if (level == 'trace' || level == 'data') return
        const contextMessage = context ? `Context: ${inspect(context, false, null)}` : ''
        console.log(`At: ${new Date().toISOString()}\nLevel: ${level}\nMessage: ${message}\n${contextMessage}`)
    }
})


test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Create user', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.create({ id, nam, othr })
    expect(user.nam).toMatch(nam)
})

test('Update nam field', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.update({ id, othr, nam: nameOther })
    expect(user.nam).toMatch(nameOther)
})

test('The nam field is really updated', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.get({ id, othr, nam })
    expect(user.nam).toMatch(nameOther)
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})

```

STDOUT:
```
Using local Java to run dynamoDB
Spawn DynamoDB 32593
Waiting for 0.0.0.0:4567..
Connected!
DynamoDB is ready
  console.log
    At: 2022-01-11T00:49:04.272Z
    Level: trace
    Message: Loading OneTable

      at Log.logger (test/debug.ts:38:17)

  console.log
    At: 2022-01-11T00:49:04.581Z
    Level: trace
    Message: OneTable createTable for "DebugTable"
    Context: {
      def: {
        AttributeDefinitions: [
          { AttributeName: 'id', AttributeType: 'S' },
          { AttributeName: 'othr', AttributeType: 'S' },
          { AttributeName: 'nam', AttributeType: 'S' }
        ],
        KeySchema: [
          { AttributeName: 'id', KeyType: 'HASH' },
          { AttributeName: 'othr', KeyType: 'RANGE' }
        ],
        GlobalSecondaryIndexes: [
          {
            IndexName: 'gsi',
            KeySchema: [ { AttributeName: 'nam', KeyType: 'HASH' } ],
            Projection: { ProjectionType: 'ALL' }
          }
        ],
        TableName: 'DebugTable',
        BillingMode: 'PAY_PER_REQUEST'
      }
    }

      at Log.logger (test/debug.ts:38:17)

  console.log
    At: 2022-01-11T00:49:04.650Z
    Level: trace
    Message: OneTable "put" "User"
    Context: {
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: '(attribute_not_exists(id)) and (attribute_not_exists(othr))',
          TableName: 'DebugTable',
          Item: {
            id: { S: 'aswpfhaeswr' },
            nam: { S: 'foo' },
            othr: { S: 'othr' },
            type: { S: 'User' },
            created: { S: '2022-01-11T00:49:04.647Z' },
            updated: { S: '2022-01-11T00:49:04.647Z' }
          },
          ReturnValues: 'NONE'
        },
        op: 'put',
        properties: {
          id: 'aswpfhaeswr',
          nam: 'foo',
          othr: 'othr',
          type: 'User',
          created: '2022-01-11T00:49:04.647Z',
          updated: '2022-01-11T00:49:04.647Z'
        }
      }
    }

      at Log.logger (test/debug.ts:38:17)

  console.log
    At: 2022-01-11T00:49:04.751Z
    Level: data
    Message: OneTable result for "put" "User"
    Context: {
      cmd: {
        ConditionExpression: '(attribute_not_exists(id)) and (attribute_not_exists(othr))',
        TableName: 'DebugTable',
        Item: {
          id: { S: 'aswpfhaeswr' },
          nam: { S: 'foo' },
          othr: { S: 'othr' },
          type: { S: 'User' },
          created: { S: '2022-01-11T00:49:04.647Z' },
          updated: { S: '2022-01-11T00:49:04.647Z' }
        },
        ReturnValues: 'NONE'
      },
      items: [
        {
          id: 'aswpfhaeswr',
          nam: 'foo',
          othr: 'othr',
          created: 2022-01-11T00:49:04.647Z,
          updated: 2022-01-11T00:49:04.647Z
        }
      ],
      op: 'put',
      properties: {
        id: 'aswpfhaeswr',
        nam: 'foo',
        othr: 'othr',
        type: 'User',
        created: '2022-01-11T00:49:04.647Z',
        updated: '2022-01-11T00:49:04.647Z'
      },
      params: { parse: true, high: true, exists: false, checked: true }
    }

      at Log.logger (test/debug.ts:38:17)

  console.log
    At: 2022-01-11T00:49:04.756Z
    Level: trace
    Message: OneTable "update" "User"
    Context: {
      trace: {
        model: 'User',
        cmd: {
          ConditionExpression: '(attribute_exists(id)) and (attribute_exists(othr))',
          ExpressionAttributeNames: { '#_0': 'updated' },
          ExpressionAttributeValues: { ':_0': { S: '2022-01-11T00:49:04.755Z' } },
          TableName: 'DebugTable',
          ReturnValues: 'ALL_NEW',
          UpdateExpression: 'set #_0 = :_0',
          Key: { id: { S: 'aswpfhaeswr' }, othr: { S: 'othr' } }
        },
        op: 'update',
        properties: {
          id: 'aswpfhaeswr',
          nam: 'bar',
          othr: 'othr',
          type: 'User',
          updated: '2022-01-11T00:49:04.755Z'
        }
      }
    }

      at Log.logger (test/debug.ts:38:17)
```

STDERR:
```
FAIL test/debug.ts (6.526 s)
  ✓ Create Table (308 ms)
  ✓ Create user (107 ms)
  ✕ Update nam field (68 ms)
  ✕ The nam field is really updated (17 ms)
  ✓ Destroy Table (22 ms)

  ● Update nam field

    expect(received).toMatch(expected)

    Expected substring: "bar"
    Received string:    "foo"

      57 |     const User = table.getModel('User')
      58 |     const user: UserType = await User.update({ id, othr, nam: nameOther })
    > 59 |     expect(user.nam).toMatch(nameOther)
         |                      ^
      60 | })
      61 |
      62 | test('The nam field is really updated', async() => {

      at Object.<anonymous> (test/debug.ts:59:22)

  ● The nam field is really updated

    expect(received).toMatch(expected)

    Expected substring: "bar"
    Received string:    "foo"

      63 |     const User = table.getModel('User')
      64 |     const user: UserType = await User.get({ id, othr, nam })
    > 65 |     expect(user.nam).toMatch(nameOther)
         |                      ^
      66 | })
      67 |
      68 | test('Destroy Table', async() => {

      at Object.<anonymous> (test/debug.ts:65:22)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        6.609 s, estimated 7 s
Ran all test suites matching /debug.ts/i.

```

**Expected behavior**
I expect the field to be updated as specified.

**Additional context**
Incidentally, for this schema
```
  primary: { hash: 'id', sort: 'nam' }
```
how should one write code to update the 'nam' field? Or the 'id' field for that matter?

**Comment by mobsense** [comment]
In DynamoDB you cannot update a PK or SK. That will create a new item.

So you need to use create with delete in a transaction.

**Comment by adrian-grajdeanu** [comment]
Right. One cannot _update_ the primary hash/sort of the item, but remove-old/add-new in a transaction. Do you have a sample code somewhere?
Anyway, this is the incidental part of the matter. Not the main issue, which remains the problem of the library currently not updating a field if it is part of the key of a lsi/gsi. This is exacerbating when that field is unique. The library removes old unique marker, adds the new unique marker, but does not update the item's field. This way the item field and the unique marker get out of sync.

**Comment by mobsense** [comment]
I'm not sure I'm following.

In your sample, the first update after the create fails because the keys for the item don't exist. If you used exists: null in the params, it would have created the item. But the update correctly fails because the item does not exist.

We cannot update a field unless the specified item exists. Because the item with the keys specified in the update does not exist, we cannot update the field.

**Comment by adrian-grajdeanu** [comment]
This is the schema:
```
primary: { hash: 'id', sort: 'othr' }, gsi: { hash: 'nam' }, // with this schema the test fails
```
This is the (first) failing tests:
```
test('Update nam field', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.update({ id, othr, nam: nameOther })
    expect(user.nam).toMatch(nameOther)
})
```
Note that ```nam``` is the field whose value is changed, the rest (```id``` and ```othr```) are provided as primary key.

This is the generated cmd:
```
        cmd: {
          ConditionExpression: '(attribute_exists(id)) and (attribute_exists(othr))',
          ExpressionAttributeNames: { '#_0': 'updated' },
          ExpressionAttributeValues: { ':_0': { S: '2022-01-11T00:49:04.755Z' } },
          TableName: 'DebugTable',
          ReturnValues: 'ALL_NEW',
          UpdateExpression: 'set #_0 = :_0',
          Key: { id: { S: 'aswpfhaeswr' }, othr: { S: 'othr' } }
        },
```

Should be:
```
        cmd: {
          ConditionExpression: '(attribute_exists(id)) and (attribute_exists(othr))',
          ExpressionAttributeNames: { '#_0': 'updated', '#_1': 'nam' },
          ExpressionAttributeValues: { ':_0': { S: '2022-01-11T00:49:04.755Z' }, ':_1': { S: 'bar' } },
          TableName: 'DebugTable',
          ReturnValues: 'ALL_NEW',
          UpdateExpression: 'set #_0 = :_0, #_1 = :_1 ',
          Key: { id: { S: 'aswpfhaeswr' }, othr: { S: 'othr' } }
        },
```
Note in the above the addition of ```#_1``` and ```:_1```

**Comment by adrian-grajdeanu** [comment]
Look at the table schema in this failing test being created in the aws console:![table-pk](https://user-images.githubusercontent.com/43449827/148881834-f909e179-e2c7-44df-8fbf-92e0448468d3.jpg)
![table-gsi](https://user-images.githubusercontent.com/43449827/148881857-762b0bca-572b-41d0-bc83-a520447141c0.jpg)
![request](https://user-images.githubusercontent.com/43449827/148881894-ed2e5360-7989-493f-b3ec-2940a18889e8.jpg)

**Comment by adrian-grajdeanu** [comment]
Digging through the code I discovered that if line 71 (in the above test/debug.ts) 
```
const user: UserType = await User.update({ id, othr, nam: nameOther })
```
is replaced with:
```
const user: UserType = await User.update({ id, othr, nam: nameOther }, {updateIndexes: true})
```
the test passes.
I'm puzzled why the updateIndexes is not by default true, why is it needed at all, and if indeed is needed, what other implications are there if I turn it to true here?

**Comment by mobsense** [comment]
I think it was coded before we were doing the attribute_exists protection and params.exists to control create via update.

The reason was that when someone does an update(), they typically never expect it to create a new item. Without updateIndexes, such an update could create a new item and leave the old item behind.

Now, and I need to think this through more slowly, ... with attribute_exists, we probably have the protection against accidental creation. 

If someone did an update with exists: null, they are explicitly taking responsibility for bypassing the attribute_exists protection and they can create a new item AND maybe leave behind the original item with the previous key values.

**Comment by adrian-grajdeanu** [comment]
Be that as it may, as the cmd is generated today it seems to me it never makes sense to do an update without { updateIndexes: true }. Doing it without clearly leads to problems from undesired results (caller asked for a field to be updated and it was silently ignored) to nasty data inconsistencies (if that field is also unique). Not only shold updateIndexes default to true, but the possibility of running with { updateIndexes: false } should not exist, because it is clearly wrong.

Lines 321-323 from Expression.js should be struck out.
```
        if (field.isIndexed && params.updateIndexes !== true && params.exists !== null) {
            //  Update indexes if explicitly requested or doing update(, {exists: null}), i.e. create.
            return;
        }
```

Same with line 1425 from README.md
```
| updateIndexes | `boolean` | Set to true to update index attributes. The default during updates is to not update index values (either primary or secondard) which are defined during create.|
```

On line 214 of Model.d.ts, the attribute should be marked deprecated and always true semantic should be explained, until it is removed in a subsequent release.

These are all occurrences of ```updateIndexes``` in the repo.
```
$ git grep -n updateIndexes
README.md:1425:| updateIndexes | `boolean` | Set to true to update index attributes. The default during updates is to not update index values (either primary or secondard) which are defined during create.|
src/Expression.js:336:        if (field.isIndexed && params.updateIndexes !== true && params.exists !== null) {
src/Model.d.ts:214:    updateIndexes?: boolean,
$
```

**Comment by mobsense** [comment]
I hear you and understand.

Let me dig deep and confirm. 

If all checks out and I've got no reason to doubt that it will, I'll checkout how to best transition to this. We may need some deprecation and runtime warnings.

**Comment by mobsense** [comment]
Looks like the attribute_exists / not exists protects us here, so we can remove updateIndexes completely.

If you omit updateIndexes and don't use exists: null, then an attempt to update a primary index will fail correctly.

If you specify exists: null, then no attribute exists test will occur and you will create a new entry as you request.

**Comment by onhate** [comment]
It looks like a quick fix here would be to only set isIndexed property of the field if it is primary https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.js#L170

```
field.isIndexed = index === 'primary'
```

as you can see isIndexed is only used to add key on get, delete and update, and also to check if needs to skip the property on update request.

this change should allow update secondary indexes properties on updates and will keep compatibility

**Comment by mobsense** [comment]
Thanks @onhate. The key question is whether it is more intuitive / safer to have updateIndexes or not.

Arguments for/against:

Not having:
* There is no special case for updating a GSI.
* If you forget updateIndexes, it will still work.
* Updating a GSI index really does function differently to the primary index. It doesn't create a new item, just a new index entry.

Having UpdateIndexes
* Safer for GSIs so you don't accidentally remove a GSI index entry

I'm in favor of removing. I believe it is simpler and closer to the DynamoDB native behavior.
