### ISSUE TITLE
Backwards pagination not working when querying global secondary indexes

### ISSUE THREAD

**Issue by rdelcampog** [sensedeep/dynamodb-onetable#269]
**Describe the bug**
Backwards pagination not working when querying global secondary indexes. If a find operation is done over a `gs1` index, the `model.prev` object has only `gs1pk` and `gs1sk` keys but no the required `pk` and `sk` keys.

Conflicting code probably located at: https://github.com/sensedeep/dynamodb-onetable/blob/96eb5843695bd65f6588ca185e6e7f50a9e23364/src/Model.js#L378-L384

**To Reproduce**

Schema:
```js
const schema = {
  version: '0.1.0',
  format: 'onetable:1.0.0',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'gs1sk' },
  },
  models: {
    Order: {
      pk: { type: String, value: 'Order#${userId}:${orderId}' },
      sk: { type: String, value: 'Order#' },
    
      orderId: { type: String, uuid: true },
      userId: { type: String, uuid: true, required: true, },
      dateCreated: { type: Date },
    
      // To allow finding all user orders, or a specific user order
      gs1pk: { type: String, value: 'User#${userId}' },
      gs1sk: { type: String, value: 'Order#${orderId}' },
    }
  }
};
```

Query:
```js
const userId = 'e4b4585e-be66-47c7-8f3d-70ab185a19d8';
const next = undefined;
const prev = undefined;
const reverse = true; // As I want orders to be date-descendent

const orders = await Order.find(
  { userId },
  {
    index: 'gs1',
    hidden: true, // Just for debug purposes
    fields: ['pk', 'sk', 'gs1pk', 'gs1sk', 'dateCreated'], // Just for debug purposes
    limit: 3,
    next,
    prev,
    reverse
  },
);

console.log(orders.next);
console.log(orders.prev);
```

This will log to console:
```js
// Next object will be the last order result keys (both primary and secondary index keys) 
{
    "pk": "Order#e4b4585e-be66-47c7-8f3d-70ab185a19d8:01FQV48GMG4R5PK7RKCSWGRY92",
    "sk": "Order#",
    "gs1pk": "User#e4b4585e-be66-47c7-8f3d-70ab185a19d8",
    "gs1sk": "Order#01FQV48GMG4R5PK7RKCSWGRY92"
}

// Prev object will be the first order result keys (only secondary index keys)
{
    "gs1pk": "User#e4b4585e-be66-47c7-8f3d-70ab185a19d8",
    "gs1sk": "Order#01FSVAAFV5QS38N2XQB0MA7M26"
}
```

Backward navigation query:
```js
const userId = 'e4b4585e-be66-47c7-8f3d-70ab185a19d8';
const next = undefined;
const prev = {
    "gs1pk": "User#e4b4585e-be66-47c7-8f3d-70ab185a19d8",
    "gs1sk": "Order#01FSVAAFV5QS38N2XQB0MA7M26"
};
const reverse = true; // As I want orders to be date-descendent

const orders = await Order.find(
  { userId },
  {
    index: 'gs1',
    hidden: true, // Just for debug purposes
    fields: ['pk', 'sk', 'gs1pk', 'gs1sk', 'dateCreated'], // Just for debug purposes
    limit: 3,
    next,
    prev,
    reverse
  },
);

console.log(orders.next);
console.log(orders.prev);
```

An exception is thrown:
```
OneError: OneTable execute failed "find" for "Order. The provided starting key is invalid
  at Table.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:553:27)
  at Generator.throw (<anonymous>)
  at rejected (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:11:65)
  at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  context: {
    err: ValidationException: The provided starting key is invalid
    at deserializeAws_json1_0QueryCommandError (/opt/nodejs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2984:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /opt/nodejs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /opt/nodejs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/opt/nodejs/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /opt/nodejs/node_modules/aws-xray-sdk-core/dist/lib/patchers/aws3_p.js:87:15
    at async /opt/nodejs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
      __type: 'com.amazon.coral.validate#ValidationException',
      '$fault': 'client',
      '$metadata': [Object]
    }
  },
  date: 2022-02-05T06:37:46.621Z
}
```

If instead of sending the client the `orders.prev` object cursor I use the following custom object, everything works fine:
```js
const prev = {
  pk: orders[0].pk,
  sk: orders[0].sk,
  gs1pk: orders[0].gs1pk,
  gs1sk: orders[0].gs1sk,
}
```

**Expected behavior**
The `model.prev` should return both global secondary index keys and primary index keys so a previous navigation query can be sent.

**Environment:**
 - OS: Mac OS 12.1
 - Node Version: v14.18.0
 - OneTable Version: v2.2.0
 - TypeScript Version: v4.5.4

**Comment by mobsense** [comment]
Thanks for the report.

Can you please post a complete test case which edits debug.ts and includes creation of test items?

Thanks
