### ISSUE TITLE
TypeError: Cannot read property 'cover' of undefined

### ISSUE THREAD

**Issue by gparonitti** [sensedeep/dynamodb-onetable#294]
Hi there,
Thank you for your work it is very precious to me and the company I work for. It speeds up coding a lot.

This Error appeared in version 2.3.2. It seems related to nested schema object. All worked well in 2.3.1 version which I reverted to, but I would like to keep updated your package 😄.

The error log:
```
2022-03-03T08:40:02.017Z	8dbde301-8fc8-43bd-9173-356ac6162b65	ERROR	TypeError: Cannot read property 'cover' of undefined
    at Model.transformReadBlock (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:925:82)
    at Model.transformReadBlock (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:925:38)
    at Model.transformReadItem (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:880:21)
    at Model.parseResponse (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:484:38)
    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:386:30)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

My schema (not complete for NDA reasons):
```javascript
export const MainTableSchema = {
  version: '1.1.0',
  format: 'onetable:1.1.0',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    GS1: { hash: 'gs1pk', sort: 'gs1sk' },
    GS2: { hash: 'gs2pk', sort: 'gs2sk' },
    GS3: { hash: 'gs3pk', sort: 'gs3sk' },
    GS4: { hash: 'gs4pk', sort: 'gs4sk' },
    GS5: { hash: 'gs5pk', sort: 'gs5sk' },
    GS6: { hash: 'gs6pk', sort: 'gs6sk' },
    GS7: { hash: 'gs7pk', sort: 'gs7sk' },
    GS8: { hash: 'gs8pk', sort: 'gs8sk' },
    GS9: { hash: 'gs9pk', sort: 'gs9sk' },
    GS10: { hash: 'gs10pk', sort: 'gs10sk' },
    GS11: { hash: 'gs11pk', sort: 'gs11sk' },
    GS12: { hash: 'gs12pk', sort: 'gs12sk' }
  },
  models: {
    Admin: {
      ...
    },
    Contributor: {
      ...
    },
    Game: {
      // Attributes indexed by primary key
      pk: { type: String, value: 'GAME#NS#${gameNamespace}' },
      sk: { type: String, value: 'GAME#NS#${gameNamespace}' },

      // Attributes indexed by GSI
      gs1pk: { type: String, value: 'GAME#ID#${gameId}' },
      gs1sk: { type: String, value: 'GAME#ID#${gameId}' },
      gs2pk: { type: String, value: 'USER#USERNAME#${authorUsername}' },
      gs2sk: { type: String, value: 'GAME#NS#${gameNamespace}' },
      gs3pk: { type: String, value: createGameTimeStampsPK('pubDate') },
      gs3sk: { type: String, value: 'GAME#PUBDATE#${pubDate}' },
      gs4pk: { type: String, value: createScoreShard('gs4') },
      gs4sk: { type: String, value: 'DESKTOP#HOT#SCORE#${hotDesktopScore}' },
      gs5pk: { type: String, value: createScoreShard('gs5') },
      gs5sk: { type: String, value: 'DESKTOP#TOP#SCORE#${topDesktopScore}' },
      gs6pk: { type: String, value: createScoreShard('gs6') },
      gs6sk: { type: String, value: 'MOBILE#HOT#SCORE#${hotMobileScore}' },
      gs7pk: { type: String, value: createScoreShard('gs7') },
      gs7sk: { type: String, value: 'MOBILE#TOP#SCORE#${topMobileScore}' },
      gs8pk: { type: String, value: createScoreShard('gs8') },
      gs8sk: { type: String, value: 'DESKTOP#HOT#SCORE#${hotDesktopScore}#GAME#NS#${gameNamespace}' },
      gs9pk: { type: String, value: createScoreShard('gs9') },
      gs9sk: { type: String, value: 'DESKTOP#TOP#SCORE#${topDesktopScore}#GAME#NS#${gameNamespace}' },
      gs10pk: { type: String, value: createScoreShard('gs10') },
      gs10sk: { type: String, value: 'MOBILE#HOT#SCORE#${hotMobileScore}#GAME#NS#${gameNamespace}' },
      gs11pk: { type: String, value: createScoreShard('gs11') },
      gs11sk: { type: String, value: 'MOBILE#TOP#SCORE#${topMobileScore}#GAME#NS#${gameNamespace}' },
      gs12pk: { type: String, value: createGameTimeStampsPK('updatedAt') },
      gs12sk: { type: String, value: 'UPDATED#${updatedAt}' },

      // Attributes projected
      assets: {
        type: Object,
        schema: {
//**************************************************************************//
//*** THIS PROPERTY CAN'T BE READ BY `Model.transformReadBlock` ***//
//**************************************************************************//
          cover: {
            type: Object,
            schema: {
              ts: { type: String },
              w400: { type: String },
              w320: { type: String },
              w144: { type: String }
            }
          },
//**************************************************************************//
//**************************************************************************//
//**************************************************************************//
          icon: {
            type: Object,
            schema: {
              ts: { type: String },
              w105: { type: String },
              w64: { type: String }
            }
          },
          video: { type: String }
        }
      },
      ...
    },
    GameDescription: {
      pk: { type: String, value: 'GAME#DESC#${gameNamespace}' },
      sk: { type: String, value: 'GAME#DESC#${gameNamespace}' },
      ...
    },
    TagGames: {
      // Attributes indexed by primary key
      pk: { type: String, value: 'TAG#NS#${tagNamespace}' },
      sk: { type: String, value: 'GAME#NS#${gameNamespace}' },

      // Attributes indexed by GSI
      gs4pk: { type: String, value: 'DESKTOP#HOT#TAG#NS#${tagNamespace}' },
      gs4sk: { type: String, value: 'DESKTOP#HOT#SCORE#${hotDesktopScore}' },
      gs5pk: { type: String, value: 'DESKTOP#TOP#TAG#NS#${tagNamespace}' },
      gs5sk: { type: String, value: 'DESKTOP#TOP#SCORE#${hotDesktopScore}' },
      gs6pk: { type: String, value: 'MOBILE#HOT#TAG#NS#${tagNamespace}' },
      gs6sk: { type: String, value: 'MOBILE#HOT#SCORE#${topDesktopScore}' },
      gs7pk: { type: String, value: 'MOBILE#TOP#TAG#NS#${tagNamespace}' },
      gs7sk: { type: String, value: 'MOBILE#TOP#SCORE#${topDesktopScore}' },
      ...
    },
    Tag: {
      // Attributes indexed by primary key
      pk: { type: String, value: getFirstCharShard('tagNamespace', 'TAGS#') },
      sk: { type: String, value: 'TAG#NS#${tagNamespace}' },
      ...
     },
    User: {
      // Attributes indexed by primary key
      pk: { type: String, value: 'USERNAME#${username}' },
      sk: { type: String, value: 'USERNAME#${username}' },

      // Attributes indexed by GSI
      gs1pk: { type: String, value: 'USER#EMAIL#${email}' },
      gs1sk: { type: String, value: 'USER#EMAIL#${email}' },
      gs2pk: { type: String, value: 'USER#ID#${userId}' },
      gs2sk: { type: String, value: 'USER#ID#${userId}' },
      gs12pk: { type: String, value: createUserTimeStampsPK('updatedAt') },
      gs12sk: { type: String, value: 'UPDATED#${updatedAt}' },
      ...
    },
    UserVote: {
      pk: { type: String, value: 'USER#VOTE#${username}'},
      sk: { type: String, value: 'GAME#${gameNamespace}#DEVICE#${device}' },
      ...
    }
  },
  params: {
    updatedField: 'updatedAt',
    createdField: 'createdAt',
    timestamps: false,
    typeField: '_model',
    isoDates: false
  }
}
```

My code (this is a kinesis analytics receiver lambda, but all the lambdas that `getItem` are affected):
```javascript
import { createAMapOfEvents, kinesisResponseMap } from '@/helpers/extraction-helper'
import { MainTable } from '@/helpers/table-helper'
import { top, hot } from '@/helpers/score-helper'

const Game = MainTable.getModel('Game')

const capitalize = string => string.charAt(0).toUpperCase() + string.slice(1)

export const calculateScore = async event => {
  console.log(JSON.stringify(event, null, 2))
  const { records } = event
  const response = { records: [] }
  for (const record of createAMapOfEvents(records)) {
    const { recordId, namespace: gameNamespace, device, upVotes, downVotes } = record
    try {
      const game = await Game.get({ gameNamespace })
      const ups = game[`${device}UpVote`] + upVotes
      const downs = game[`${device}DownVote`] + downVotes
      const hotScore = hot(ups, downs, game.pubDate)
      const topScore = top(ups, downs)
      const payload = {
        gameNamespace,
        [`hot${capitalize(device)}Score`]: hotScore,
        [`top${capitalize(device)}Score`]: topScore,
        [`${device}UpVote`]: ups,
        [`${device}DownVote`]: downs
      }
      await Game.update(payload)
      response.records.push(kinesisResponseMap({ recordId }, 'Ok'))
    } catch (error) {
      console.log('Error:', error)
      response.records.push(kinesisResponseMap({ recordId }, 'DeliveryFailed'))
    }
  }
  return response
}
```

cheers!

**Comment by mobsense** [comment]
As per the issue template, can you please create a minimal test case in the debug.ts so we can more quickly address your issue.

**Comment by mobsense** [comment]
We may have committed a fix to your issue to the repository. Please test and let us know. 

It is hard to know because we need your test case via debug.ts to verify.

**Comment by gparonitti** [comment]
Hi I have applied your patch and it works. Regarding the test case, sorry but I was clueless if the problem was originated by nested schema objects. 
Thank you very much for the prompt fix! Cheers!

**Comment by teyckmans** [comment]
@mobsense running into this issue also.

Appears to be happening on the second level of nesting.

We updated to 2.3.2 for the nested Date handling fix, with this fixed all looks good again for us :+1: 

Any idea when this will make it's way into a released version?
