### ISSUE TITLE
GSI is not updated when combined property is changed

### ISSUE THREAD

**Issue by pop-srw** [sensedeep/dynamodb-onetable#301]
**Describe the bug**
I can't find details about how the update function can affect GSI value, as document described
`
The value property defines a literal string template that is used to compute the attribute value. This is useful for computing key values from other properties, creating compound (composite) sort keys or for packing fields into a single DynamoDB attribute when using GSIs.
`
I expect GSI which created by state property to be updated when the state property is changed.

**Cut/Paste**
src/debug.test.ts
```
import { DocumentClient } from "aws-sdk/clients/dynamodb";
import { Credentials } from "aws-sdk";
import { Table, Entity, OneSchema } from "dynamodb-onetable";

const schema = {
  version: "0.0.1",
  indexes: {
    primary: { hash: "pk", sort: "sk" },
    gs1: { hash: "gs1pk", sort: "gs1sk" },
  },
  models: {
    User: {
      pk: { type: String, value: "USER#${id}" },
      sk: { type: String, value: "USER" },
      gs1pk: { type: String, value: "USER" },
      gs1sk: { type: String, value: "STATE#${state}" },
      id: { type: String, required: true },
      name: { type: String, required: true },
      state: { type: String, enum: ["created", "deleted"] },
    },
  },
};

type UserType = Entity<typeof schema.models.User>;

const ddb = new DocumentClient({
  convertEmptyValues: true,
  endpoint: `http://localhost:${process.env.DYNAMODB_PORT}`,
  region: "local",
  credentials: new Credentials({
    accessKeyId: "test",
    secretAccessKey: "test",
  }),
});

const tableName = "test-tbl";

const table = new Table({
  client: ddb,
  name: tableName,
  schema: schema,
  logger: (level, message, context) => {
    if (level == "data") return;
    console.log(`${new Date().toLocaleString()}: ${level}: ${message}`);
    console.log(JSON.stringify(context, null, 4) + "\n");
  },
});

const User = table.getModel<UserType>("User");

describe("GSI update test", () => {
  beforeAll(async () => {
    if (!(await table.exists())) {
      await table.createTable();
      expect(await table.exists()).toBe(true);
    }
  });

  afterAll(async () => {
    await table.deleteTable("DeleteTableForever");
    expect(await table.exists()).toBe(false);
  });

  test("GSI should be created", async () => {
    await User.create(
      {
        id: "user01",
        name: "test",
        state: "created",
      },
      {
        exists: false,
      }
    );

    const { Item: item } = await ddb
      .get({
        TableName: "test-tbl",
        Key: {
          pk: "USER#user01",
          sk: "USER",
        },
      })
      .promise();

    expect(item).toMatchObject({
      pk: "USER#user01",
      sk: "USER",
      gs1pk: "USER",
      gs1sk: "STATE#created",
      id: "user01",
      name: "test",
      state: "created",
    });
  });

  test("GSI should be updated", async () => {
    await User.update(
      {
        id: "user01",
      },
      {
        set: {
          state: "deleted",
        },
        exists: true,
      }
    );

    const { Item: item } = await ddb
      .get({
        TableName: "test-tbl",
        Key: {
          pk: "USER#user01",
          sk: "USER",
        },
      })
      .promise();

    expect(item).toMatchObject({
      pk: "USER#user01",
      sk: "USER",
      gs1pk: "USER",
      gs1sk: "STATE#deleted",
      id: "user01",
      name: "test",
      state: "deleted",
    });
  });
});

```

Output log
```
$ yarn test debug
yarn run v1.22.5
$ jest --runInBand debug
Determining test suites to run...Using local Java to run dynamoDB
Spawn DynamoDB 16829
  console.log
    3/16/2022, 8:06:52 PM: trace: Loading OneTable

      at Log.logger (src/debug.test.ts:44:13)

  console.log
    undefined

      at Log.logger (src/debug.test.ts:45:13)

  console.log
    3/16/2022, 8:06:53 PM: trace: OneTable createTable for "test-tbl"

      at Log.logger (src/debug.test.ts:44:13)

  console.log
    {
        "def": {
            "AttributeDefinitions": [
                {
                    "AttributeName": "pk",
                    "AttributeType": "S"
                },
                {
                    "AttributeName": "sk",
                    "AttributeType": "S"
                },
                {
                    "AttributeName": "gs1pk",
                    "AttributeType": "S"
                },
                {
                    "AttributeName": "gs1sk",
                    "AttributeType": "S"
                }
            ],
            "KeySchema": [
                {
                    "AttributeName": "pk",
                    "KeyType": "HASH"
                },
                {
                    "AttributeName": "sk",
                    "KeyType": "RANGE"
                }
            ],
            "GlobalSecondaryIndexes": [
                {
                    "IndexName": "gs1",
                    "KeySchema": [
                        {
                            "AttributeName": "gs1pk",
                            "KeyType": "HASH"
                        },
                        {
                            "AttributeName": "gs1sk",
                            "KeyType": "RANGE"
                        }
                    ],
                    "Projection": {
                        "ProjectionType": "ALL"
                    }
                }
            ],
            "TableName": "test-tbl",
            "BillingMode": "PAY_PER_REQUEST"
        }
    }

      at Log.logger (src/debug.test.ts:45:13)

  console.log
    3/16/2022, 8:06:53 PM: trace: OneTable "put" "User"

      at Log.logger (src/debug.test.ts:44:13)

  console.log
    {
        "trace": {
            "model": "User",
            "cmd": {
                "ConditionExpression": "(attribute_not_exists(#_0)) and (attribute_not_exists(#_1))",
                "ExpressionAttributeNames": {
                    "#_0": "pk",
                    "#_1": "sk"
                },
                "TableName": "test-tbl",
                "Item": {
                    "pk": "USER#user01",
                    "sk": "USER",
                    "gs1pk": "USER",
                    "gs1sk": "STATE#created",
                    "id": "user01",
                    "name": "test",
                    "state": "created",
                    "_type": "User"
                },
                "ReturnValues": "NONE"
            },
            "op": "put",
            "properties": {
                "pk": "USER#user01",
                "sk": "USER",
                "gs1pk": "USER",
                "gs1sk": "STATE#created",
                "id": "user01",
                "name": "test",
                "state": "created",
                "_type": "User"
            }
        }
    }

      at Log.logger (src/debug.test.ts:45:13)

  console.log
    3/16/2022, 8:06:53 PM: trace: OneTable "update" "User"

      at Log.logger (src/debug.test.ts:44:13)

  console.log
    {
        "trace": {
            "model": "User",
            "cmd": {
                "ConditionExpression": "(attribute_exists(#_0)) and (attribute_exists(#_1))",
                "ExpressionAttributeNames": {
                    "#_0": "pk",
                    "#_1": "sk",
                    "#_2": "state",
                    "#_3": "gs1pk",
                    "#_4": "id"
                },
                "ExpressionAttributeValues": {
                    ":_0": "deleted",
                    ":_1": "USER",
                    ":_2": "user01"
                },
                "TableName": "test-tbl",
                "ReturnValues": "ALL_NEW",
                "UpdateExpression": "set #_2 = :_0, #_3 = :_1, #_4 = :_2",
                "Key": {
                    "pk": "USER#user01",
                    "sk": "USER"
                }
            },
            "op": "update",
            "properties": {
                "pk": "USER#user01",
                "sk": "USER",
                "gs1pk": "USER",
                "id": "user01",
                "_type": "User"
            }
        }
    }

      at Log.logger (src/debug.test.ts:45:13)

  console.log
    3/16/2022, 8:06:53 PM: trace: OneTable deleteTable for "test-tbl"

      at Log.logger (src/debug.test.ts:44:13)

  console.log
    undefined

      at Log.logger (src/debug.test.ts:45:13)

 FAIL  src/debug.test.ts
  GSI update test
    ✓ GSI should be created (113 ms)
    ✕ GSI should be updated (54 ms)

  ● GSI update test › GSI should be updated

    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

    @@ -1,8 +1,8 @@
      Object {
        "gs1pk": "USER",
    -   "gs1sk": "STATE#deleted",
    +   "gs1sk": "STATE#created",
        "id": "user01",
        "name": "test",
        "pk": "USER#user01",
        "sk": "USER",
        "state": "deleted",

      118 |       .promise();
      119 |
    > 120 |     expect(item).toMatchObject({
          |                  ^
      121 |       pk: "USER#user01",
      122 |       sk: "USER",
      123 |       gs1pk: "USER",

      at Object.<anonymous> (src/debug.test.ts:120:18)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.739 s, estimated 2 s
Ran all test suites matching /debug/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
I created two tests. For the first test, I create user object, the GSI is created correctly with state of "created". For the second test, I updated the user object with state of "deleted", the state is changed but the GSI sort key is still using "created" value.

**Environment (please complete the following information):**
 - OS - Ubuntu 18.04.2 LTS
 - Node Version - v14.17.4
 - OneTable Version - v2.3.3
 - TypeScript Version - v4.4.4

**Comment by mobsense** [comment]
The reason is that you are not providing a gs1sk. Your template requires the {state} which you are not providing in the properties.  Consequently, DynamoDB cannot locate your GSI item to update.

Note: if you change a GSI pk/sk value, you create a new item.

**Comment by pop-srw** [comment]
Thank you so much. I can make it work by using the code you provided.
```
await User.update(
  {
    id: "user01",
    state: "deleted",
  },
  {
    exists: true,
  }
);
```

I have a question what the different between

**Comment by mobsense** [comment]
The first set of parameters provide the keys to retrieve the item AND the properties to update.

The second form via {set}, will only provide the item to update. It is typically not used and is used more with the {add}. 

So when you update items, you must always provide the keys (or ingredient key values if using value templates) via the properties.

```
await User.update({id: userId, balance: 50})
await User.update({id: userId}, {add: {balance: 10.00}})
await User.update({id: userId}, {set: {status: '{active}'}})
```
