### ISSUE TITLE
Unable to mapping non-required fields

### ISSUE THREAD

**Issue by kuro0993** [sensedeep/dynamodb-onetable#306]
I am sorry that my English is so bad.

**Describe the bug**

When a model field that is not required and a map is specified is defined in the schema, an error will occur if the create method is called with the corresponding field undefined.

* Schema Sample (based on test/schemas/mappedSchema.ts)
```
    models: {
        User: {
            primaryHash: { type: String, value: 'us#${id}', map: 'pk' },
            primarySort: { type: String, value: 'us#', map: 'sk' },
            id:          { type: String, generate: 'ulid' },
            name:        { type: String, map: 'nm' },
            email:       { type: String, map: 'em' },
            status:      { type: String, map: 'st' },
            remarks:         { type: String, map: 'rs' },

            //  Properties packed into the "data" attribute projected to the gs1 secondary index
            address:     { type: String, map: 'data.address' },
            city:        { type: String, map: 'data.city' },
            zip:         { type: String, map: 'data.zip' },

            //  Find by type or email
            gs1pk:     { type: String, value: 'ty#us', map: 'pk1' },
            gs1sk:     { type: String, value: 'us#${email}', map: 'sk1' },
        }
    },

```

* Source excerpts that result in errors (based on test/mapping-and-packing.ts)
```
test('Create', async() => {
    User = table.getModel('User')
    user = await User.create({
        name: 'Peter Smith',
        status: 'active',
        email: 'peter@example.com',
        // remarks: '',                                  <= undefined
        address: '444 Cherry Tree Lane',
        city: 'Paris',
        zip: '1234567',
    })
    console.log(user);
    expect(user).toMatchObject({
        name: 'Peter Smith',
        status: 'active',
    })
})

```

* Error message
```
OneTableArgError: Missing properties for mapped data field "data" in model "User"
```

**Environment (please complete the following information):**
 - OS : Win10 (WSL2)
 - Node Version: v14.19.0
 - OneTable Version: 2.3.3
 - TypeScript Version: 4.6.2

---

I believe the issue stems from the following lines;
I think we need to consider required parameters.
* `src/Expression.js` 
https://github.com/sensedeep/dynamodb-onetable/blob/b1112e36a3bf9f57b717bb3074b772552a47ca21/src/Expression.js#L107-L109

I tried to fix it. I passed some test, but my PC is too heavy to pass the whole test.
For the time being, I will only report the issue.

**Comment by mobsense** [comment]
That code should only be used for nested mapped attributes. i.e. those under "data.*".  The reason is the entire 'data' object must be serialized and written by DynamoDB. So you can't update just one field.

However, remarks should be able to be updated as it isn't nested. 

I've tested this and it seems to work fine.

Can you please follow the template and post a test case that demonstrates this issue for a non-nested property.

**Comment by kuro0993** [comment]
Sorry.
The Schema Sample was wrong.

Yor are right, there is a problem with the nested mapped attributes.

Here is the test code for the problem.

**Cut/Paste**

debug.ts
```
/*
    debug.ts - Just for debug

    Edit your test case here and invoke via: "jest debug"

    Or run VS Code in the top level directory and just run.
 */
import {AWS, Client, Entity, Match, Model, Table, print, dump, delay} from './utils/init'
import { OneSchema } from '../src/index.js'

jest.setTimeout(7200 * 1000)

//  Change with your schema
const schema: OneSchema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
        gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    },
    models: {
        User: {
            pk:          { type: String, value: '${_type}#' },
            sk:          { type: String, value: '${_type}#${id}' },

            gs1pk:       { type: String, value: '${_type}#' },
            gs1sk:       { type: String, value: '${_type}#${id}' },

            name:        { type: String },
            email:       { type: String },
            id:          { type: String, generate: 'ulid' },

            test1:       { type: String, map: 'data.test1' },
            test2:       { type: String, map: 'data.test2' },
        }
    }
}

//  Change your table params as required
const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema,
    logger: true,
})

//  This will create a local table
test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Success Pattern', async() => {
    let User = table.getModel('User')
    let users = await User.create({
      name: 'Peter Smith',
      email: 'peter@example.com',
      id: '1',
      test1: 'aaa',
      test2: 'bbb',
    })
})

test('Failer Pattern', async() => {
    let User = table.getModel('User')
    let users = await User.create({
      name: 'Bob',
      email: 'Bob@example.com',
      id: '2',
      test1: 'aaa',
      // test2: 'bbb',       <-- undefined
    })
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```
result
```
Determining test suites to run...Using local Java to run dynamoDB
Spawn DynamoDB 18568
Waiting for 0.0.0.0:4567...
Connected!
DynamoDB is ready
 FAIL  test/debug.ts (7.205 s)
  ✓ Create Table (508 ms)
  ✓ Success Pattern (114 ms)
  ✕ Failer Pattern (1 ms)
  ✓ Destroy Table (35 ms)

  ● Failer Pattern

    OneTableArgError: Missing properties for mapped data field "data" in model "User"

      106 |             for (let [att, props] of Object.entries(this.mapped)) {
      107 |                 if (Object.keys(props).length != this.model.mappings[att].length) {
    > 108 |                     throw new OneTableArgError(`Missing properties for mapped data field "${att}" in model "${this.model.name}"`)
          |                           ^
      109 |                 }
      110 |             }
      111 |             for (let [k,v] of Object.entries(this.mapped)) {

      at Expression.prepare (src/Expression.js:108:27)
      at new Expression (src/Expression.js:16:14)
      at Model.putItem (src/Model.js:821:26)
      at Model.create (src/Model.js:508:33)
      at Object.<anonymous> (test/debug.ts:67:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        7.278 s
Ran all test suites matching /test\/debug.ts/i.
npm ERR! Test failed.  See above for more details.
```

**Comment by mobsense** [comment]
Sorry to be unclear. If you are updating an attribute that is mapped to a nested map, you must always update all properties of that map. This is the design and required by how DynamoDB updates object attributes.

So if you want to update test1, you must supply test2. Otherwise, DynamoDB will delete the value of test2.

This only applies for nested mapped attributes. If they are top level, you don't need to update all attributes.

**Comment by kuro0993** [comment]
Thank you.
I would reconsider the schema design.
