### ISSUE TITLE
LSI projection

### ISSUE THREAD

**Issue by peniqliotuv** [sensedeep/dynamodb-onetable#392]
**Describe the bug**

LSI projections are not allowed, despite being a feature of Dynamo (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LSI.html#LSI.Projections). When setting the `project` property on an index with `type: 'local'`, you get the following error 
```
OneTableArgError: Unexpected project definition for LSI
    at Schema.validateSchema (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/dynamodb-onetable/dist/cjs/Schema.js:104:31)
    at Schema.setSchemaInner (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/dynamodb-onetable/dist/cjs/Schema.js:46:18)
    at new Schema (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/dynamodb-onetable/dist/cjs/Schema.js:32:14)
    at new Table (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/dynamodb-onetable/dist/cjs/Table.js:89:23)
    at Object.<anonymous> (/Users/jt/fragment/workspaces/global-services/services/global-api/scripts/models/index.ts:41:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.mod._compile (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/esbuild-runner/src/hook.ts:53:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.Module._extensions.<computed> [as .ts] (/Users/jt/fragment/workspaces/global-services/services/global-api/node_modules/esbuild-runner/src/hook.ts:56:7)
```
**To Reproduce**
```
export const schema = {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
    primary: {
      hash: 'pk',
      sort: 'sk',
    },
    lsi1: { hash: 'pk', sort: 'l1', type: 'local', project: 'all' }, // <--- this fails
  },
  models: {
   ...
  } as const,
} as const;
```

**Comment by KennyDizi** [comment]
@peniqliotuv we don't need to set hash for LSI index, keep it simple like that: lsi1: { sort: 'lsi1sk', type: 'local' }

**Comment by peniqliotuv** [comment]
> @peniqliotuv we don't need to set hash for LSI index, keep it simple like that: lsi1: { sort: 'lsi1sk', type: 'local' }

If it's not required, should it be omitted from the options to prevent misconfiguring?
