### ISSUE TITLE
config.endpointProvider is not set - Version 2.5.1 only

### ISSUE THREAD

**Issue by louislatreille** [sensedeep/dynamodb-onetable#427]
OneTableError: OneTable execute failed "put" for "user. config.endpointProvider is not set.

**To Reproduce**

1. Clone this repository. Must test against the current master branch in the repository.
2. Edit your reproducible, MINIMAL, stand-alone test case into the test/debug.ts file.
3. Run via `jest debug` or run VS code in the top level directory.

**Cut/Paste**

```
import {Entity, Table} from './utils/init'
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";

jest.setTimeout(7200 * 1000)

//  Change with your schema
const schema = {
    format: "onetable:1.1.0",
    version: "1.0.0",
    indexes: {
      primary: { hash: "pk", sort: "sk" },
    },
    models: {
      user: {
        pk: { type: String, value: "U#${userId}" },
        sk: { type: String, value: "-" },
        userId: { type: String, required: true },
        username: { type: String, required: true },
      },
    } as const,
  };

//  Change your table params as required
const table = new Table({
    name: 'oneTableTest',
    client: new DynamoDBClient({ region: "us-east-1" }),
    partial: true,
    schema,
    logger: true,
})

type UserItem = Entity<typeof schema.models.user>;

test('Test', async() => {
    const userModel = table.getModel<UserItem>("user");

    await userModel.create({
      userId: "testUser",
      username: "testUserName",
    });
})
```

```
 console.log
    error OneTable exception in "put" on "user" {
        "err": {},
        "trace": {
            "model": "user",
            "cmd": {
                "ConditionExpression": "(attribute_not_exists(#_0)) and (attribute_not_exists(#_1))",
                "ExpressionAttributeNames": {
                    "#_0": "pk",
                    "#_1": "sk"
                },
                "TableName": "oneTableTest",
                "Item": {
                    "pk": "U#testUser",
                    "sk": "-",
                    "userId": "testUser",
                    "username": "testUserName",
                    "_type": "user"
                },
                "ReturnValues": "NONE"
            },
            "op": "put",
            "properties": {
                "pk": "U#testUser",
                "sk": "-",
                "userId": "testUser",
                "username": "testUserName",
                "_type": "user"
            }
        }
    }

      at Log.defaultLogger (src/Table.js:1279:25)

 FAIL  test/debug.ts (7.414 s)
  ✕ Test (45 ms)

  ● Test

    OneTableError: OneTable execute failed "put" for "user. client[DocumentClientMethods[op]] is not a function

      661 |                     this.log.error(`OneTable exception in "${op}" on "${model}"`, {err, trace})
      662 |                 }
    > 663 |                 throw new OneTableError(`OneTable execute failed "${op}" for "${model}. ${err.message}`, {
          |                       ^
      664 |                     code, err, trace,
      665 |                 })
      666 |             }

      at Table.execute (src/Table.js:663:23)
      at Model.run (src/Model.js:353:39)
      at Model.putItem (src/Model.js:914:27)
      at Model.create (src/Model.js:526:33)
      at Object.<anonymous> (test/debug.ts:44:21)
```

**Expected behavior**
I would expect my create method to just work.

**Additional context**
I've removed the part of the test file that connect to the local DynamoDB, as I don't have that configured.

**Comment by mobsense** [comment]
What version of Node are you using on Lambda?

Node 18 uses the AWS SDK V3 by default.

**Comment by mobsense** [comment]
If you are using the AWS SDK V3, you need different initialization (as per docs).

Use:

```
const client = new Dynamo({client: new DynamoDBClient({region: 'us-east-1'})})
```

We created our AWS SDK V3 support before AWS added the DocumentClient to the V3 SDK. OneTable currently does not Document client interface but goes directly to the core AWS API.

**Comment by revmischa** [comment]
I'm doing this but still get the error
```ts
export const dbClient = new Dynamo({
  client: new DynamoDBClient({
    // enabled for testing - jest-dynalite
    ...(process.env.MOCK_DYNAMODB_ENDPOINT
      ? {
          endpoint: process.env.MOCK_DYNAMODB_ENDPOINT,
          sslEnabled: false,
          region: "local",
        }
      : {
          region: process.env.AWS_REGION || "us-east-1",
        }),
  }),
});
```

**Comment by mobsense** [comment]
This is working for me, so we need more details:

- What AWS SDK are you using - what exact version?
- What Lambda Node version are you using?
- When testing locally, does npm run test work on your PC?
- Can you post a complete, stand-alone, Lambda test that we can test non-locally in AWS?

**Comment by revmischa** [comment]
Upgrading to latest AWS SDK v3 fixed the issue for me

**Comment by mobsense** [comment]
Can you say:

- What AWS version worked
- What AWS version did not work
- What node version are you using?

**Comment by revmischa** [comment]
> Can you say:
> 
> * What AWS version worked 
Latest - `~3.235.0`
> * What AWS version did not work
`3.58.0`
> * What node version are you using?
Node 14 & 16

**Comment by louislatreille** [comment]
Closing the issue now, as we have resolved it!
