### ISSUE TITLE
How to update an item by PK using `Model.update`?

### ISSUE THREAD

**Issue by vhuty** [sensedeep/dynamodb-onetable#429]
It's not clear from the [documentation](https://doc.onetable.io/api/model/methods/#update) how to use `Model.update` properly.
For example, I have the following schema:
```
{
  format: "onetable:1.1.0",
  version: "0.0.1",
  indexes: {
    primary: { hash: "PK", sort: "SK" },
  },
  params: {
    typeField: "_type",
    timestamps: true,
    isoDates: true,
    createdField: "createdAt",
    updatedField: "updatedAt",
  },
  models: {
    Payment: {
      PK: { type: String, value: "payment#${id}", hidden: true },
      SK: { type: String, value: "createdAt#${createdAt}", hidden: true },
      id: { type: String, required: true },
      status: { type: String },
      createdAt: { type: Date, required: true },
      updatedAt: { type: Date, required: true },
      processedAt: { type: Date },
    },
  },
}
```

I need to update the `status` field for the item with the id="123456":
1. Should I set `status` along with `id` as the first argument into the `Model.payment`?
```
Payment.update({ id: "123456", status: "PAID" });
```
2. Or should I specify just the `status` as the first argument and use where clause with `id`?
```
Payment.update({ status: "PAID" }, {
  where: "${id} = @{id}",
  substitutions: { id: "123456" }
});
```
3. Or should I specify just the `id` as the first argument and use `params.set` with `status` specified?
```
Payment.update({ id: "123456" }, { set: { status: "PAID" } });
```
4. Or should I leave first argument empty and use `params.where` and `params.set`?
```
Payment.update({}, {
  set: { status: "PAID" }, 
  where: "${id} = @{id}", 
  substitutions: { id: "123456" } 
});
```

Which one is appropriate for updating by PK?

**Comment by mobsense** [comment]
Much is preference.

I use (1) in most cases:

    Payment.update({ id: "123456", status: "PAID" });

This is the simplest approach. With this pattern, you provide the properties to be updated, including all the fields that are required to calculate the item keys.

Where clauses are typically used for more complex conditional queries. 

Lastly, "set" is mostly used to perform atomic expressions like incrementing a counter.

**Comment by vhuty** [comment]
Thanks for the answer @mobsense.
With this approach:
```
Payment.update({ id: "123456", status: "PAID" });
```

I receive the following error:
```
{
    "errorType": "OneTableError",
    "errorMessage": "Empty hash key. Check hash key and any value template variable references.",
    "code": "MissingError",
    "name": "OneTableError",
    "context": {
        "properties": {
            "status": "DONE",
            "processedAt": "2022-12-21T22:30:40.313Z",
            "updatedAt": "2022-12-21T22:30:40.313Z",
            "_type": "Payment"
        },
        "rec": {
            "updatedAt": "2022-12-21T22:30:40.313Z",
            "processedAt": "2022-12-21T22:30:40.313Z",
            "status": "DONE",
            "_type": "Payment"
        }
    },
    "date": "2022-12-21T22:30:40.315Z",
    "stack": [
        "OneTableError: Empty hash key. Check hash key and any value template variable references.",
        "    at Model.prepareProperties (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:1015:19)",
        "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:882:31)",
        "    at Generator.next (<anonymous>)",
        "    at /opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71",
        "    at new Promise (<anonymous>)",
        "    at __awaiter (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:4:12)",
        "    at Model.updateItem (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:870:16)",
        "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:698:31)",
        "    at Generator.next (<anonymous>)",
        "    at /opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71"
    ]
}
```

Should I specify the `PK: "payment#123456"` instead of just `id` according to the schema above?

**Comment by vhuty** [comment]
> Thanks for the answer @mobsense. With this approach:
> 
> ```
> Payment.update({
>   id: "123456",
>   status: "DONE",
>   processedAt: new Date()
> });
> ```
> 
> I receive the following error:
> 
> ```
> {
>     "errorType": "OneTableError",
>     "errorMessage": "Empty hash key. Check hash key and any value template variable references.",
>     "code": "MissingError",
>     "name": "OneTableError",
>     "context": {
>         "properties": {
>             "status": "DONE",
>             "processedAt": "2022-12-21T22:30:40.313Z",
>             "updatedAt": "2022-12-21T22:30:40.313Z",
>             "_type": "Payment"
>         },
>         "rec": {
>             "updatedAt": "2022-12-21T22:30:40.313Z",
>             "processedAt": "2022-12-21T22:30:40.313Z",
>             "status": "DONE",
>             "_type": "Payment"
>         }
>     },
>     "date": "2022-12-21T22:30:40.315Z",
>     "stack": [
>         "OneTableError: Empty hash key. Check hash key and any value template variable references.",
>         "    at Model.prepareProperties (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:1015:19)",
>         "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:882:31)",
>         "    at Generator.next (<anonymous>)",
>         "    at /opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71",
>         "    at new Promise (<anonymous>)",
>         "    at __awaiter (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:4:12)",
>         "    at Model.updateItem (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:870:16)",
>         "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:698:31)",
>         "    at Generator.next (<anonymous>)",
>         "    at /opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71"
>     ]
> }
> ```
> 
> Should I specify the `PK: "payment#123456"` instead of just `id` according to the schema above?

Following this approach I get:
```
{
    "errorType": "OneTableError",
    "errorMessage": "OneTable execute failed \"update\" for \"PaymentTransaction. The provided key element does not match the schema",
    "code": "ValidationException",
    "name": "OneTableError",
    "context": {
        "err": {
            "errorType": "ValidationException",
            "errorMessage": "The provided key element does not match the schema",
            "name": "ValidationException",
            "$fault": "client",
            "$metadata": {
                "httpStatusCode": 400,
                "requestId": "...",
                "attempts": 1,
                "totalRetryDelay": 0
            },
            "__type": "com.amazon.coral.validate#ValidationException",
            "message": "The provided key element does not match the schema",
            "error@context": {
                "_ns_name": "AWSXRay",
                "id": 0,
                "segment": {
                    "trace_id": "...",
                    "id": "...",
                    "start_time": 1671701275.301,
                    "name": "facade",
                    "in_progress": false,
                    "counter": 1,
                    "service": {
                        "runtime": "node",
                        "runtime_version": "v16.16.0",
                        "version": "unknown",
                        "name": "unknown"
                    },
                    "aws": {
                        "xray": {
                            "sdk": "X-Ray for Node.js",
                            "sdk_version": "3.4.0",
                            "package": "aws-xray-sdk-core"
                        }
                    },
                    "facade": true,
                    "subsegments": []
                }
            },
            "stack": [
                "ValidationException: The provided key element does not match the schema",
                "    at throwDefaultError (/opt/nodejs/node_modules/dynamodb-onetable/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
                "    at deserializeAws_json1_0UpdateItemCommandError (/opt/nodejs/node_modules/dynamodb-onetable/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2719:51)",
                "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
            ]
        },
        "trace": {
            "model": "Payment",
            "cmd": {
                "ConditionExpression": "(attribute_exists(#_0)) and (attribute_exists(#_1))",
                "ExpressionAttributeNames": {
                    "#_0": "PK",
                    "#_1": "SK",
                    "#_2": "updatedAt",
                    "#_3": "processedAt",
                    "#_4": "status"
                },
                "ExpressionAttributeValues": {
                    ":_0": {
                        "S": "2022-12-22T09:27:56.067Z"
                    },
                    ":_1": {
                        "S": "2022-12-22T09:27:56.066Z"
                    },
                    ":_2": {
                        "S": "DONE"
                    }
                },
                "TableName": "payments",
                "ReturnValues": "ALL_NEW",
                "UpdateExpression": "set #_2 = :_0, #_3 = :_1, #_4 = :_2",
                "Key": {
                    "PK": {
                        "S": "payment#123456"
                    }
                }
            },
            "op": "update",
            "properties": {
                "PK": "payment#123456",
                "updatedAt": "2022-12-22T09:27:56.067Z",
                "processedAt": "2022-12-22T09:27:56.066Z",
                "status": "DONE",
                "_type": "Payment"
            }
        }
    },
    "date": "2022-12-22T09:27:56.330Z",
    "stack": [
        "OneTableError: OneTable execute failed \"update\" for \"PaymentTransaction. The provided key element does not match the schema",
        "    at Table.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:590:27)",
        "    at Generator.throw (<anonymous>)",
        "    at rejected (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:11:65)",
        "    at clsBind (/opt/nodejs/node_modules/cls-hooked/context.js:172:17)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    ]
}
```

**Comment by mobsense** [comment]
You should (and we do) just use:

    Payment.update({ id: "123456", status: "PAID" });

If your schema specifies the PK/SK to use value templates, then those fields will be expanded using the properties you provide. 

You can provide explicit PK/SK values, but in general, it is best to provide the fields and let the value templates calculate the PK/SK values.

I can't see what is not working from the snippets you posted. Use {log: true} to see what is actually being sent to DynamoDB. Also, recheck your schema.

**Comment by vhuty** [comment]
I have an error when executing this query, but that is another case. Gonna create one more issue. Thank you!
