### ISSUE TITLE
[BUG]: createTable() fails with "TypeError: Cannot read property 'createTable' of undefined"

### ISSUE THREAD

**Issue by ericmarcos** [sensedeep/dynamodb-onetable#43]
**Describe the bug**

I'm trying to create a DynamoDB Table using the `createTable` method from the `Table` class but it fails with "TypeError: Cannot read property 'createTable' of undefined". See how to reproduce it and full error message below.

Node version: v14.6.0
Project deps:
```json
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.17.0",
    "@aws-sdk/util-dynamodb": "^3.17.0",
    "@babel/polyfill": "^7.12.1",
    "core-js": "^3.13.0",
    "dynamodb-onetable": "^1.4.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.2"
  }
```

**To Reproduce**
```javascript
import Dynamo from 'dynamodb-onetable/Dynamo'
import { Table } from 'dynamodb-onetable'
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'

const client = new Dynamo({ client: new DynamoDBClient({ region: 'dev', endpoint: 'http://localhost:8000' }) })

const table = new Table({
    client: client,
    name: 'TestLocal2',
    uuid: 'ulid',
    delimiter: '#',
    schema: {
        indexes: {
            primary: { hash: 'pk', sort: 'sk' },
            gs1:     { hash: 'gs1pk', sort: 'gs1sk', follow: true },
        },
        models: {
            User: {
                pk:          { type: String, value: 'USR#${id}' },
                sk:          { type: String, value: 'USR#${id}' },
                id:          { type: String, uuid: true },
                name:        { type: String, required: true },
                status:      { type: String, default: 'active' },
                zip:         { type: String },
            },
            Event: {
                pk:          { type: String, value: 'USR#${userId}' },
                sk:          { type: String, value: 'EVT#${id}' },
                id:          { type: String, uuid: true },
                userId:      { type: String, required: true },
                name:        { type: String, required: true },
                gs1pk:       { type: String, value: 'EVT#${id}' },
                gs1sk:       { type: String, value: 'EVT#${id}' },
            }
        }
    },
    logger: (type, message, context) => {
        if (type == 'trace' || type == 'data') return
        console.log(type, message, JSON.stringify(context, null, 4))
    }
})

const User = table.getModel('User')
const Event = table.getModel('Event')

const main = async () => {
    try {
        await table.createTable()
    } catch (e) {
        console.log(e)
    }
}

main()
```

I compile this script with Babel: `babel index.js --out-dir dist`

And run it with `node dist/index.js`

Which results in this error:

```
TypeError: Cannot read property 'createTable' of undefined
    at Table.<anonymous> (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/dynamodb-onetable/dist/cjs/Table.js:256:46)
    at Generator.next (<anonymous>)
    at /some-path/2021-05-27-dynamodb-onetable-test/node_modules/dynamodb-onetable/dist/cjs/Table.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/dynamodb-onetable/dist/cjs/Table.js:7:12)
    at Table.createTable (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/dynamodb-onetable/dist/cjs/Table.js:182:16)
    at _callee$ (/some-path/2021-05-27-dynamodb-onetable-test/dist/index.js:138:26)
    at tryCatch (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/some-path/2021-05-27-dynamodb-onetable-test/node_modules/regenerator-runtime/runtime.js:118:21)
```

**Expected behavior**
A new Table "TestLocal2" is created.

**Screenshots**

**Environment (please complete the following information):**
- OS: macOS Big Sur
- Node Version: 14.6.0

**Additional context**
I'm using the local version of DynamoDB (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)

**Comment by mobsense** [comment]
Thanks. Looks like a AWS V3 issue as it works with V2.

**Comment by mobsense** [comment]
That is confirmed.  Just committed a solution with updated sample/crud that uses create/delete database. v1.4.3.

Will push to NPM soon.

**Comment by ericmarcos** [comment]
I confirm it works =)
Thanks again for the quick fix!

**Comment by mobsense** [comment]
Our goal is to knock down issues as quickly as possible. I hate repos that have dozens or scores of unfixed issues that fester!
