### ISSUE TITLE
Unable to fetch entity by `PK` without `SK` specified using `Model.get`

### ISSUE THREAD

**Issue by vhuty** [sensedeep/dynamodb-onetable#430]
Consider the following schema:
```
{
  format: "onetable:1.1.0",
  version: "0.0.1",
  indexes: {
    primary: { hash: "PK", sort: "SK" },
  },
  params: {
    typeField: "_type",
    timestamps: true,
    isoDates: true,
    createdField: "createdAt",
    updatedField: "updatedAt",
  },
  models: {
    Payment: {
      PK: { type: String, value: "payment#${id}", hidden: true },
      SK: { type: String, value: "user#${userId}", hidden: true },
      id: { type: String, required: true },
      userId: { type: String, required: true },
      status: { type: String },
      createdAt: { type: Date, required: true },
      updatedAt: { type: Date, required: true },
      processedAt: { type: Date },
    },
  },
}
```

When trying to fetch a record by the `id`:
```
Payment.get({ id: "123456" });
```

The following error happens:
```
{
    "errorType": "OneTableError",
    "errorMessage": "OneTable execute failed \"find\" for \"Payment. Query key condition not supported",
    "code": "ValidationException",
    "name": "OneTableError",
    "context": {
        "err": {
            "errorType": "ValidationException",
            "errorMessage": "Query key condition not supported",
            "name": "ValidationException",
            "$fault": "client",
            "$metadata": {
                "httpStatusCode": 400,
                "requestId": "...",
                "attempts": 1,
                "totalRetryDelay": 0
            },
            "__type": "com.amazon.coral.validate#ValidationException",
            "message": "Query key condition not supported",
            "error@context": {
                "_ns_name": "AWSXRay",
                "id": 0,
                "segment": {
                    "trace_id": "...",
                    "id": "...",
                    "start_time": 1671790717.768,
                    "name": "facade",
                    "in_progress": false,
                    "counter": 1,
                    "service": {
                        "runtime": "node",
                        "runtime_version": "v16.16.0",
                        "version": "unknown",
                        "name": "unknown"
                    },
                    "aws": {
                        "xray": {
                            "sdk": "X-Ray for Node.js",
                            "sdk_version": "3.4.0",
                            "package": "aws-xray-sdk-core"
                        }
                    },
                    "facade": true,
                    "subsegments": []
                }
            },
            "stack": [
                "ValidationException: Query key condition not supported",
                "    at throwDefaultError (/opt/nodejs/node_modules/dynamodb-onetable/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
                "    at deserializeAws_json1_0QueryCommandError (/opt/nodejs/node_modules/dynamodb-onetable/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2140:51)",
                "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
            ]
        },
        "trace": {
            "model": "Payment",
            "cmd": {
                "ExpressionAttributeNames": {
                    "#_0": "PK",
                    "#_1": "SK",
                    "#_2": "id"
                },
                "ExpressionAttributeValues": {
                    ":_0": {
                        "S": "payment#123456"
                    },
                    ":_1": {
                        "S": "user#"
                    },
                    ":_2": {
                        "S": "123456"
                    }
                },
                "FilterExpression": "#_2 = :_2",
                "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_1)",
                "TableName": "payments",
                "ConsistentRead": false,
                "Limit": 2,
                "ScanIndexForward": true
            },
            "op": "find",
            "properties": {
                "PK": "payment#123456",
                "SK": {
                    "begins": "user#"
                },
                "id": "123456"
            }
        }
    },
    "date": "2022-12-23T10:18:38.751Z",
    "stack": [
        "OneTableError: OneTable execute failed \"find\" for \"Payment. Query key condition not supported",
        "    at Table.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:590:27)",
        "    at Generator.throw (<anonymous>)",
        "    at rejected (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Table.js:11:65)",
        "    at clsBind (/opt/nodejs/node_modules/cls-hooked/context.js:172:17)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    ]
}
```

**Comment by vhuty** [comment]
How to get an item just by partition key (`id`) without using indexes?

**Comment by mobsense** [comment]
That should work. Get falls back to use find under the hood if you don't provide a complete SK and it then returns the first matching result.

Did a Model.find() work?

The Dynamo query looks okay at first glance, it is doing a find/query and the Key conditions and filter expressions look fine.

Can you create a test case for us to reproduce.

**Comment by vhuty** [comment]
I'm gonna provide a test case for this. But still, how to perform just the `GetItem` DynamoDB operation on a table specifying only a value of the **simple** primary key not using any index under the hood?

Since `get` just "[wraps the DynamoDB getItem method](https://doc.onetable.io/api/model/methods/#get)", why does it make find/query under the hood? Isn't it ambiguous?

**Comment by vhuty** [comment]
It turned out that the field specified as the `hash` (`"PK"`) of the primary index in the schema definition was not used in the actual DDL for the `payments` table. So bad configuration caused this issue. I'm closing it.

Thank you, @mobsense, for your help!
