### ISSUE TITLE
Invalid prev value returned when paginating on gsi's

### ISSUE THREAD

**Issue by AliOatley** [sensedeep/dynamodb-onetable#433]
**Describe the bug**

When paginating using a gsi, such as like this:
```
let firstPage = await User.find({accountId}, {limit, index: 'somegsi'})
let secondPage = await User.find({accountId}, {limit, next: firstPage.next, index: 'somegsi'})
let previousPage = await User.find({accountId}, {limit, prev: secondPage.prev, index: 'somegsi'})
```
 
The prev object is missing pk and sk unlike the next object. As a result, passing the prev object to a find call results in an empty array as a response.
```
next: {"sk":"***","gsi1_pk":"***","pk":"***","gsi1_sk":"***"}
prev: {"gsi1_pk":"***","gsi1_sk":"***"}
```

**To Reproduce**

https://github.com/AliOatley/dynamodb-onetable/blob/feature-debug/test/debug.ts

```
// Test 1 is successful when no index is passed
test('Test1', async () => {
    let log = true
    let User = table.getModel('User')
    await User.create({name: 'John', email: 'john@gmail.com'})
    await User.create({name: 'Tim', email: 'tim@gmail.com'})
    let first = await User.find({}, {limit: 1})
    let second = await User.find({}, {limit: 1, next: first.next})
    let previous = await User.find({}, {limit: 1, prev: second.prev})

    expect(second.prev).toHaveProperty('pk')
    expect(second.prev).toHaveProperty('sk')
})

// Test 2 fails when index is passed
test('Test2', async () => {
    let log = true
    let User = table.getModel('User')
    await User.create({name: 'Ann', email: 'ann@gmail.com'})
    await User.create({name: 'Bob', email: 'bob@gmail.com'})
    let first = await User.find({}, {limit: 1, index: 'gs1', log})
    let second = await User.find({}, {limit: 1, index: 'gs1', next: first.next, log})
    let previous = await User.find({}, {limit: 1, index: 'gs1', prev: second.prev, log})

    expect(second.prev).toHaveProperty('pk')
    expect(second.prev).toHaveProperty('sk')
})
```

```
FAIL test/debug.ts
  ● Console

    console.log
      info OneTable "find" "User" {
          "trace": {
              "model": "User",
              "cmd": {
                  "ExpressionAttributeNames": {
                      "#_0": "gs1pk",
                      "#_1": "gs1sk"
                  },
                  "ExpressionAttributeValues": {
                      ":_0": "User#"
                  },
                  "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
                  "TableName": "DebugTable",
                  "ConsistentRead": false,
                  "IndexName": "gs1",
                  "Limit": 1,
                  "ScanIndexForward": true
              },
              "op": "find",
              "properties": {
                  "gs1pk": "User#",
                  "gs1sk": {
                      "begins": "User#"
                  }
              }
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

    console.log
      info OneTable result for "find" "User" {
          "cmd": {
              "ExpressionAttributeNames": {
                  "#_0": "gs1pk",
                  "#_1": "gs1sk"
              },
              "ExpressionAttributeValues": {
                  ":_0": "User#"
              },
              "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
              "TableName": "DebugTable",
              "ConsistentRead": false,
              "IndexName": "gs1",
              "Limit": 0,
              "ScanIndexForward": true,
              "ExclusiveStartKey": {
                  "gs1pk": "User#",
                  "sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4",
                  "pk": "User#",
                  "gs1sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4"
              }
          },
          "items": [
              {
                  "name": "John",
                  "email": "john@gmail.com",
                  "id": "01GPHHRVMB7YKJQQ8STK5ZFCK4"
              }
          ],
          "op": "find",
          "properties": {
              "gs1pk": "User#",
              "gs1sk": {
                  "begins": "User#"
              }
          },
          "params": {
              "parse": true,
              "high": true,
              "limit": 1,
              "index": "gs1",
              "log": true,
              "checked": true
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

    console.log
      info OneTable "find" "User" {
          "trace": {
              "model": "User",
              "cmd": {
                  "ExpressionAttributeNames": {
                      "#_0": "gs1pk",
                      "#_1": "gs1sk"
                  },
                  "ExpressionAttributeValues": {
                      ":_0": "User#"
                  },
                  "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
                  "TableName": "DebugTable",
                  "ConsistentRead": false,
                  "IndexName": "gs1",
                  "Limit": 1,
                  "ScanIndexForward": true,
                  "ExclusiveStartKey": {
                      "gs1pk": "User#",
                      "sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4",
                      "pk": "User#",
                      "gs1sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4"
                  }
              },
              "op": "find",
              "properties": {
                  "gs1pk": "User#",
                  "gs1sk": {
                      "begins": "User#"
                  }
              }
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

    console.log
      info OneTable result for "find" "User" {
          "cmd": {
              "ExpressionAttributeNames": {
                  "#_0": "gs1pk",
                  "#_1": "gs1sk"
              },
              "ExpressionAttributeValues": {
                  ":_0": "User#"
              },
              "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
              "TableName": "DebugTable",
              "ConsistentRead": false,
              "IndexName": "gs1",
              "Limit": 0,
              "ScanIndexForward": true,
              "ExclusiveStartKey": {
                  "gs1pk": "User#",
                  "sk": "User#01GPHHRVPX8F4CM44N2WB15Q52",
                  "pk": "User#",
                  "gs1sk": "User#01GPHHRVPX8F4CM44N2WB15Q52"
              }
          },
          "items": [
              {
                  "name": "Tim",
                  "email": "tim@gmail.com",
                  "id": "01GPHHRVPX8F4CM44N2WB15Q52"
              }
          ],
          "op": "find",
          "properties": {
              "gs1pk": "User#",
              "gs1sk": {
                  "begins": "User#"
              }
          },
          "params": {
              "parse": true,
              "high": true,
              "limit": 1,
              "index": "gs1",
              "next": {
                  "gs1pk": "User#",
                  "sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4",
                  "pk": "User#",
                  "gs1sk": "User#01GPHHRVMB7YKJQQ8STK5ZFCK4"
              },
              "log": true,
              "checked": true
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

    console.log
      info OneTable "find" "User" {
          "trace": {
              "model": "User",
              "cmd": {
                  "ExpressionAttributeNames": {
                      "#_0": "gs1pk",
                      "#_1": "gs1sk"
                  },
                  "ExpressionAttributeValues": {
                      ":_0": "User#"
                  },
                  "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
                  "TableName": "DebugTable",
                  "ConsistentRead": false,
                  "IndexName": "gs1",
                  "Limit": 1,
                  "ScanIndexForward": false,
                  "ExclusiveStartKey": {
                      "gs1pk": "User#",
                      "gs1sk": "User#01GPHHRVPX8F4CM44N2WB15Q52"
                  }
              },
              "op": "find",
              "properties": {
                  "gs1pk": "User#",
                  "gs1sk": {
                      "begins": "User#"
                  }
              }
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

    console.log
      error OneTable exception in "find" on "User" {
          "err": {
              "message": "Exclusive Start Key must have same size as table's key schema",
              "code": "ValidationException",
              "time": "2023-01-11T23:13:48.684Z",
              "requestId": "475606f5-2751-[43](https://github.com/AliOatley/dynamodb-onetable/actions/runs/3897525971/jobs/6655299412#step:8:44)54-9426-ef4e8494d62c",
              "statusCode": 400,
              "retryable": false,
              "retryDelay": 49.50682646915771
          },
          "trace": {
              "model": "User",
              "cmd": {
                  "ExpressionAttributeNames": {
                      "#_0": "gs1pk",
                      "#_1": "gs1sk"
                  },
                  "ExpressionAttributeValues": {
                      ":_0": "User#"
                  },
                  "KeyConditionExpression": "#_0 = :_0 and begins_with(#_1, :_0)",
                  "TableName": "DebugTable",
                  "ConsistentRead": false,
                  "IndexName": "gs1",
                  "Limit": 1,
                  "ScanIndexForward": false,
                  "ExclusiveStartKey": {
                      "gs1pk": "User#",
                      "gs1sk": "User#01GPHHRVPX8F4CM[44](https://github.com/AliOatley/dynamodb-onetable/actions/runs/3897525971/jobs/6655299412#step:8:45)N2WB15Q52"
                  }
              },
              "op": "find",
              "properties": {
                  "gs1pk": "User#",
                  "gs1sk": {
                      "begins": "User#"
                  }
              }
          }
      }

      at Log.defaultLogger (src/Table.js:1296:25)
          at runMicrotasks (<anonymous>)

  ● Test2

    OneTableError: OneTable execute failed "find" for "User. Exclusive Start Key must have same size as table's key schema

      669 |                     this.log.error(`OneTable exception in "${op}" on "${model}"`, {err, trace})
      670 |                 }
    > 671 |                 throw new OneTableError(`OneTable execute failed "${op}" for "${model}. ${err.message}`, {
          |                       ^
      672 |                     code,
      673 |                     err,
      674 |                     trace,

      at Table.execute (src/Table.js:671:23)
          at runMicrotasks (<anonymous>)
      at Model.run (src/Model.js:365:22)
      at Model.queryItems (src/Model.js:991:16)
      at Model.find (src/Model.js:626:16)
      at Object.<anonymous> (test/debug.ts:72:20)

PASS test/marshall.ts
PASS test/typescript-count.ts
PASS test/regress/low-level-query-with-gsi.ts
PASS test/packed-attribute-with-follow.ts
PASS test/legacy.ts
PASS test/regress/update-gsi-keys.ts
PASS test/crypto.ts
PASS test/timestamps.ts
PASS test/scan.ts
PASS test/typescript-infer.ts
PASS test/transform.ts
PASS test/fallback.ts
PASS test/ulid.ts
PASS test/value-template.ts
PASS test/create-destroy-table.ts
PASS test/parallel-scan.ts
PASS test/mock.ts
PASS test/stats.ts
PASS test/default.ts
PASS test/array-items.ts
PASS test/typescript-extras.ts
PASS test/stub.ts
PASS test/misc.ts
PASS test/utils.ts
PASS test/dummy.ts

Summary of all failing tests
FAIL test/debug.ts
  ● Test2

    OneTableError: OneTable execute failed "find" for "User. Exclusive Start Key must have same size as table's key schema

      669 |                     this.log.error(`OneTable exception in "${op}" on "${model}"`, {err, trace})
      670 |                 }
    > 671 |                 throw new OneTableError(`OneTable execute failed "${op}" for "${model}. ${err.message}`, {
          |                       ^
      672 |                     code,
      673 |                     err,
      674 |                     trace,

      at Table.execute (src/Table.js:671:23)
          at runMicrotasks (<anonymous>)
      at Model.run (src/Model.js:365:22)
      at Model.queryItems (src/Model.js:991:16)
      at Model.find (src/Model.js:626:16)
      at Object.<anonymous> (test/debug.ts:72:20)


Test Suites: 1 failed, 52 passed, 53 total
Tests:       1 failed, 357 passed, 358 total
Snapshots:   0 total
Time:        [50](https://github.com/AliOatley/dynamodb-onetable/actions/runs/3897525971/jobs/6655299412#step:8:51).2[77](https://github.com/AliOatley/dynamodb-onetable/actions/runs/3897525971/jobs/6655299412#step:8:78) s
Ran all test suites.
Error: Process completed with exit code 1.
```

**Expected behavior**
I should be able to use the prev object returned from a find call in order to go to the previous page of results.

**Environment (please complete the following information):**
 - Node Version: 16.x
 - OneTable Version: 2.5.1

**Comment by dev-embedthis** [comment]
I think you are using next when you should be using prev.

You used:

```
    let first = await User.find({}, {limit: 1})
    let second = await User.find({}, {limit: 1, next: first.next})
    let previous = await User.find({}, {limit: 1, next: second.prev})
```

Should be:

```
    let first = await User.find({}, {limit: 1})
    let second = await User.find({}, {limit: 1, next: first.next})
    let previous = await User.find({}, {limit: 1, prev: second.prev})
```

**Comment by AliOatley** [comment]
Ok I had a typo in my example. I have fixed it and updated the original issue description.  Same issue.

**Comment by dev-embedthis** [comment]
Can you be more specific. What value of prev in what statement?

It works fine for me and I can step forward and back.

**Comment by dev-embedthis** [comment]
This works for us as expected:
```
    await User.create({name: 'John', email: 'john@gmail.com'})
    await User.create({name: 'Tim', email: 'tim@gmail.com'})
    let first = await User.find({}, {limit: 1})
    let second = await User.find({}, {limit: 1, next: first.next})
    let previous = await User.find({}, {limit: 1, prev: second.prev})

    dump("FIRST", first)
    dump("SECOND", second)
    dump("PREV", previous)
```

**Comment by AliOatley** [comment]
As stated above, the issue is related specifically with using the index param to paginate on a gsi.  So yes test 1 in my exampland your example do work because they are not paginating on a gsi.  Now if you actually take a look at the logs from Test 2 you'll see that the prev value being used is missing the pk and sk fields which then results in the error which is also shown above in the logs.

```
"ExclusiveStartKey": {
                      "gs1pk": "User#",
                      "gs1sk": "User#01GPHHRVPX8F4CM44N2WB15Q52"
                  }
```

Additionally, I provided a link to the code so you can actually go and see that the test really did fail.

**Comment by dev-embedthis** [comment]
This is the reason we (and the issue template) request a complete debug.ts test case.

It avoids these misunderstandings due to incomplete issues. It saves huge amounts of time on both sides.

**Comment by AliOatley** [comment]
I filled out the template and provided all of the information you have just asked for, so I am not sure what your point is. Could you please read all of the information provided?

**Comment by dev-embedthis** [comment]
The template asks for a debug.ts that we can actually run. Your link is just to the standard empty debug.ts

So we have to reconstruct from your logs what we "guess" you are doing. Because we can't run a sample that demonstrates the issue. Hence, with your typo, we get things wrong.

This then causes us to spend 30-60+ minutes more on each issue that we would if you provided a complete, test case. This is less than ideal.

**Comment by AliOatley** [comment]
https://github.com/AliOatley/dynamodb-onetable/blob/feature-debug/test/debug.ts

**Comment by AliOatley** [comment]
^

**Comment by dev-embedthis** [comment]
Thank you. That helps. 

When we captured that link before it was the standard debug.ts

**Comment by dev-embedthis** [comment]
Turns out, undocumented by AWS, that pagination via Exclusive Start Key must also include the primary hash key.

Including those keys, then makes it work. 

Thanks for persisting and the debug.ts. Solved easily with that.

Will commit a fix and will be included in the next release.

**Comment by AliOatley** [comment]
That is great news, I'm glad we were able to align on the details.
