### ISSUE TITLE
[BUG]: Unable to create GSI's without sort key

### ISSUE THREAD

**Issue by kunalfleethawks** [sensedeep/dynamodb-onetable#58]
**Describe the bug**
DynamodB allows GSI's to be created (from Console) without sort key. But when we use this library we are not able to create GSI without SORT key.
**To Reproduce**
I tried to reproduce the issue using the sample provided in you repository - crud. You can take following scrip as reference
and execute it. It will not allow to create table and throw error 

Make sure `TestCrud` table does not exists before running following programs

ERROR
```
(node:87375) UnhandledPromiseRejectionWarning: ValidationException: Attribute name must be specified.
```

Script to test.
```
/*
    Demonstrate simple CRUD with OneTable
 */
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { Table } from "dynamodb-onetable";
//  For AWS V3
import Dynamo from "dynamodb-onetable/Dynamo";

const client = new Dynamo({
  client: new DynamoDBClient({
   // region: "ap-south-1",
    region: "local",
    endpoint:"http://localhost:8000"
  }),
});
/*
    Single-table schema and setup. This is used for general access and by `createTable`
 */
const table = new Table({
  name: "TestCrud",
  client: client,
  uuid: "ulid",
  delimiter: "#",
  logger: true,
  schema: {
    indexes: {
      primary: { hash: "pk", sort: "sk" },
      userName: { hash: "name"},
    },
    models: {
      User: {
        pk: { type: String, value: "user#${id}" },
        sk: { type: String, value: "user#${id}" },
        id: { type: String, uuid: true },
        name: { type: String },
        status: { type: String, default: "active" },
        zip: { type: String }
      },
    },
  },
});
//  Create a model to manage User entities
const User = table.getModel("User");
async function main() {
  if (!(await table.exists())) {
    await table.createTable();
  }
  
}
main();

```

LOGS 

```
(base) Kunals-MacBook-Air:crud kunaldeshmukh$ node dist/index1.js 
info Dynamo createTable for "TestCrud" {
    "def": {
        "AttributeDefinitions": [
            {
                "AttributeName": "pk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "sk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "name",
                "AttributeType": "S"
            },
            {
                "AttributeType": "S"
            }
        ],
        "KeySchema": [
            {
                "AttributeName": "pk",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "sk",
                "KeyType": "RANGE"
            }
        ],
        "GlobalSecondaryIndexes": [
            {
                "IndexName": "userName",
                "KeySchema": [
                    {
                        "AttributeName": "name",
                        "KeyType": "HASH"
                    },
                    {
                        "KeyType": "RANGE".  ### HERE IS THE ISSUE - WHERE SORT KEY IS GOING EMPTY.  THIS OBJECT SHOULD NOT BE THERE
                    }
                ],
                "Projection": {
                    "ProjectionType": "ALL"
                }
            }
        ],
        "TableName": "TestCrud",
        "BillingMode": "PAY_PER_REQUEST"
    }
}
(node:87839) UnhandledPromiseRejectionWarning: ValidationException: Attribute name must be specified.
    at deserializeAws_json1_0CreateTableCommandError (/Users/kunaldeshmukh/Downloads/test/crud/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:972:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/kunaldeshmukh/Downloads/test/crud/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/kunaldeshmukh/Downloads/test/crud/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/kunaldeshmukh/Downloads/test/crud/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /Users/kunaldeshmukh/Downloads/test/crud/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Dynamo.send (file:///Users/kunaldeshmukh/Downloads/test/crud/node_modules/dynamodb-onetable/dist/mjs/Dynamo.js:77:16)
    at async Dynamo.createTable (file:///Users/kunaldeshmukh/Downloads/test/crud/node_modules/dynamodb-onetable/dist/mjs/Dynamo.js:22:16)
    at async Table.createTable (file:///Users/kunaldeshmukh/Downloads/test/crud/node_modules/dynamodb-onetable/dist/mjs/Table.js:248:20)
    at async main (file:///Users/kunaldeshmukh/Downloads/test/crud/dist/index1.js:46:5)
(node:87839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:87839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**

As per AWS documentation we can create GSI without sort key here is the documentation : https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-6.html

Library should allow to create GSI without SORT key.

**Screenshots**

**Environment (please complete the following information):**
 - MAC
 - 12x

**Additional context**

**Comment by mobsense** [comment]
Thanks for an excellent bug report!  Everthing we need to be able to reproduce it. We have a fix coming. Should be released tomorrow.

**Comment by mobsense** [comment]
We've fixed a couple of related issues. Please try with 1.5.0.

**Comment by kunalfleethawks** [comment]
Thanks for quick turnaround. Its working
