### ISSUE TITLE
[BUG]: Unable to use `begins` condition with `Model.find` in TypeScript

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#71]
**Describe the bug**
It is unclear how to properly use a `begins` condition when using the `Model.find` APIs.

This results in a compile error:
```
export const getEventsByDriverId = async (driverId: string, filter?: Filter): Promise<AWSEvent[]> => {
  const sk = { begins: { sk: buildPrefix(filter) } }
  const results = await EventModel.find({ driverId, sk  }, { tunnel, index: 'gs2' })
  return results as AWSEvent[]
}
```

This results in `.for is not iterable` error.
```
export const getEventsByDriverId = async (driverId: string, filter?: Filter): Promise<AWSEvent[]> => {
  const tunnel = { begins: { sk: buildPrefix(filter) } }
  const results = await EventModel.find({ driverId }, { tunnel, index: 'gs2' })
  return results as AWSEvent[]
}
```

**Comment by mobsense** [comment]
Can you please simplify down your samples to be stand-alone.  I'd like to get a code snippet that we can run.

The samples/typescript/src/index.ts has a sample.

```
    let from = new Date()
    from.setMonth(from.getMonth() - 1)
    let invoices = await Invoice.find({}, {
        tunnel: { between: {
            gs1sk: [`invoice#${from.toISOString()}`, `invoice#${new Date().toISOString()}`],
        } },
        index: 'gs1',
        follow: true,
    })

```

**Comment by bytekast** [comment]
sure. here's a simple version:

```
const driverId = '12345'
const tunnel = { begins: { sk: 'MyEvent#MyModel#MyOperation#2021' } }
const results = await EventModel.find({ driverId }, { tunnel, index: 'gs2' })
```

Here's the error:
```
{"errorType":"TypeError","errorMessage":".for is not iterable","stack":["TypeError: .for is not iterable","    at Xt.tunnelProperties (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:841:29)","    at Xt.transformProperties (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:817:14)","    at Xt.prepareProperties (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:770:24)","    at Xt.queryItems (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:636:27)","    at Xt.find (/var/node_modules/dynamodb-onetable/dist/mjs/Model.js:528:27)","    at sO (/var/src/db.ts:84:36)","    at oO (/var/src/resolver.ts:7:38)","    at Runtime.handler (/opt/nodejs/node_modules/@sentry/serverless/src/awslambda.ts:274:18)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

```

**Comment by bytekast** [comment]
same error here:

```
const driverId = '12345'
const tunnel = { begins: { sk: 'MyEvent#MyModel#MyOperation#2021' } }
const results = await table.queryItems({ driverId }, { tunnel, index: 'gs2' })
```

**Comment by mobsense** [comment]
Thank you. Found the issue. We'll patch this.

The fix is to change Object.values to Object.entries

```
-            for (let [kind, settings] of Object.values(params.tunnel)) {
+           for (let [kind, settings] of Object.entries(params.tunnel)) {
```

**Comment by mobsense** [comment]
Fixed in 1.5.5

**Comment by bytekast** [comment]
awesome. thanks!

**Comment by mobsense** [comment]
Can you use params.log == true with a logger as described in the README and post the actual dynamodb query.

Also please post your schema. Hard to know what is not working right without seeing the schema and the actual query command being generated.

**Comment by bytekast** [comment]
I think I know what's going on here....

```
  const tunnel = prefixFilter ? { begins: { sk: prefixFilter } } : null
  const results = await EventModel.find({ model, modelId }, { tunnel, index: 'gs1', reverse: true, log: true })
```

`model` is an attribute used both in the partition key and the sort key. when tunnel is null, the sort key gets auto populated with the `model` value even though that isn't the intended behavior.

here's the trace:

```
1626412031269	2021-07-16T05:07:11.268Z	47a243ed-af3d-4995-bd5f-6432fec89ada	INFO	info Dynamo "find" "Event" {
    "trace": {
        "cmd": {
            "ExpressionAttributeNames": {
                "#_0": "sk",
                "#_1": "model",
                "#_2": "modelId",
                "#_3": "gs1pk",
                "#_4": "_type"
            },
            "ExpressionAttributeValues": {
                ":_0": {
                    "S": "#route"
                },
                ":_1": {
                    "S": "route"
                },
                ":_2": {
                    "S": "Yi39uLPSRgNjymCcH"
                },
                ":_3": {
                    "S": "model#route#Yi39uLPSRgNjymCcH"
                },
                ":_4": {
                    "S": "Event"
                }
            },
            "FilterExpression": "(#_1 = :_1) and (#_2 = :_2) and (#_4 = :_4)",
            "KeyConditionExpression": "begins_with(#_0, :_0) and #_3 = :_3",
            "TableName": "argus",
            "ConsistentRead": false,
            "IndexName": "gs1",
            "ScanIndexForward": false
        },
        "op": "find",
        "properties": {
            "sk": {
                "begins": "#route"
            },
            "model": "route",
            "modelId": "Yi39uLPSRgNjymCcH",
            "gs1pk": "model#route#Yi39uLPSRgNjymCcH",
            "_type": "Event"
        },
        "params": {
            "parse": true,
            "high": true,
            "index": "gs1",
            "reverse": true,
            "log": true,
            "checked": true
        }
    }
}
```

**Comment by mobsense** [comment]
Can you post your schema or redacted portions?

**Comment by bytekast** [comment]
```
const Schema = {
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'sk' },
    gs2: { hash: 'gs2pk', sort: 'sk' },
  },
  models: {
    Event: {
      pk: { type: String, value: 'event#${id}' },
      sk: { type: String, value: '${detail-type}#${model}#${operation}#${time}' }, // Allows fast filter with begins_with
      id: { type: String, required: true },
      'detail-type': { type: String, required: true },
      detail: { type: Object, required: true },
      source: { type: String, required: true },
      time: { type: String, required: true },

      // Optional time to live
      ttl: { type: Number, required: false },

      // Flattened from event.detail
      model: { type: String, required: true },
      operation: { type: String, required: true },

      // GSI - Search events by model + id. Eg Route#123, Order#abc, etc.
      gs1pk: { type: String, value: 'model#${model}#${modelId}' },

      // GSI - Search events by driverId when driver is not the event model
      gs2pk: { type: String, value: 'driver#${driverId}' },
    },
  },
}

```

**Comment by mobsense** [comment]
Thanks. What is prefixFilter, model and modelId set to when you call the API.

**Comment by bytekast** [comment]
model = route
modelId = Yi39uLPSRgNjymCcH
prefixFilter = null

**Comment by mobsense** [comment]
So tunnel is null?

**Comment by bytekast** [comment]
yep.

**Comment by bytekast** [comment]
if I provide a valid `prefixFilter` it works fine

when omitted, it looks like onetable automatically adds a `"begins": "#route"` sk, which is why the query is return zero matches

**Comment by mobsense** [comment]
Okay, I think we need better doc on this one.

If you do not provide the variables to complete the sort key, i.e. some of the ${var} references are unresolved, then OneTable will take the resolved portion and implicitly use a `begins` with on that portion.

**Comment by mobsense** [comment]
You are not providing: ${operation}#${time}

**Comment by bytekast** [comment]
but i don't want to provide those prefixes. i want the query to return all of the items without filtering the sort key

**Comment by mobsense** [comment]
Do you want ZERO SK?  i.e. only the PK?

**Comment by bytekast** [comment]
yep. so if `prefixFilter` is null, don't add a sort key

**Comment by mobsense** [comment]
When you use value templates, the PK and SK are created for you from the properties you provide. If you provide an explicit PK or SK, they are used instead. 

I'm doing this from memory, so forgive me if I'm wrong here. But ...

If the `sk` property is undefined in the properties, the value template will be used. If it is null, then the value template will not be used.  Let me confirm this.

So I think you need to include:

Model.find({sk: null, ....

Let me check this.

**Comment by mobsense** [comment]
Just confirmed that. Set sk to null.  

Normally users at least want a sk prefix of some kind. In single table / multi-tenant design, the PK may be the account ID and the leading SK prefix is used to differentiate between various entities.

**Comment by bytekast** [comment]
ok, will try that. thanks!

**Comment by bytekast** [comment]
looks like it worked! appreciate it!

**Comment by mobsense** [comment]
The log: true reveals ALL ;-)
